NaluCFD/Nalu

CMakeLists.txt
unit_tests.C
unit_tests/UnitTest1ElemCoordCheck.C
unit_tests/UnitTestHexSCVDeterminant.C
unit_tests/UnitTestUtils.C
unit_tests/UnitTestUtils.h

Demonstration unit-test creates a mesh with 1 element per processor,
verifies that each element is a unit cube by looking at nodal coordinates.

Basic unit-test infrastructure.

---

unit_tests/UnitTestHex27FaceNodeOrdering.C
unit_tests/UnitTestUtils.C
unit_tests/UnitTestUtils.h

Add a unit test to check that the consistency of ip face node relations are correct. This resolves #22

Add unit test for checking Hex 27 ip node relations

---

unit_tests.C
unit_tests/UnitTestBasicKokkos.C

These unit-tests don't interact with or modify nalu algorithms. They
show some simple kokkos operations such as creating views,
performing parallel_for loops, etc.

Add unit-tests that show simple kokkos usage.

---

unit_tests/UnitTestHexMasterElements.C

Made a class 'MasterElementHexSerial', which declares/creates the mesh,
then changed 'TEST' functions to 'TEST_F', which are actually member
methods of the MasterElementHexSerial class so they can refer to the
mesh and other members of that class.
In this case it saves a few lines of duplicated code for each test,
not huge, but demonstrates a handy gtest feature which can remove
a lot of duplication in some cases.
@rcknaus and @spdomin make sure you're happy with the readability of this. If not, no big deal.
If looking at the diff that github displays, click the 'split' view. This diff is hard to follow in 'unified' mode.

Demonstrate unit-test fixture.

---

unit_tests/UnitTestKokkosViews.C
unit_tests/UnitTestUtils.C
unit_tests/UnitTestUtils.h

Stefan, take a look at the 2 unit-tests in this commit, if you don't mind. I've tried to mimic the calculation you proposed, however I don't know how to assert correctness.
The two tests can be run like this:
mpirun -np 1 unittestX --gtest_filter=Hex8Mesh.indexing_raw_arrays
mpirun -np 1 unittestX --gtest_filter=Hex8Mesh.indexing_views
gtest reports runtime. I haven't run these on any interesting platforms, but for a release build on the linux blade it appears as though the views version is a hair faster than the raw-arrays version.

Unit-test comparing a calculation with and without kokkos views.

---

include/user_functions/BoundaryLayerPerturbationAuxFunction.h
src/LowMachEquationSystem.C
src/user_functions/BoundaryLayerPerturbationAuxFunction.C

* This initial condition adds solenoidal velocity field perturbations to a
power law boundary layer profile, with z the wall-normal coordinate.

Boundary layer perturbation user IC

---

cmake/CTestTestfile.cmake
cmake/ctest_prepare_tests.cmake

xml files were added for 16 of the tests during the Epetra deprecation. CTest is now aware of these new files.

Update ctest prepare after Epetra deprecation and new xml files 

---

unit_tests/UnitTestKokkosViews.C

Add the necessary header file in UnitTestsKokkosViews.C to fix the
compilation error.

Fix compilation error in OSX

---

unit_tests/UnitTestKokkosViews.C
unit_tests/UnitTestUtils.C

This refactoring supports our design experimentation related to
element-algorithms.
* Adds two classes that mimic element-algorithms:
TestElemAlgorithmWithVectors, TestElemAlgorithmWithViews
* Illustrates the scratch-array resizing strategy which finds max
nodes-per-elem and num-integ-points prior to the bucket loop and
performs max resize, making subsequent resize operations fast.
* Illustrates Kokkos views with shared-memory-views as prototyped
by Christian in a separate repo.
* Encapsulates looping mechanisms as described in recent meeting.
* Some 'kokkos-helper' stuff (typedefs, small functions etc) are at
the top of the file, essentially similar to the stuff that
Christian had in the KokkosInterface.h header in his repo.
* The test 'main' functions are at the bottom of the file, this …

Refactored unit-tests in UnitTestKokkosViews.C.

---

unit_tests/UnitTestBasicKokkos.C
unit_tests/UnitTestKokkosViews.C

The version of the element-algorithm that uses std::vectors for
scratch arrays (TestElemAlgorithmWithVectors) can not execute correctly
in true multi-threaded mode since the vectors can't feasibly be
allocated on a per-thread basis.
Thus, this version of the element-algorithm is now restricted to
explicitly *not* run multi-threaded.
The version of the element-algorithm that uses Kokkos::views for
scratch arrays (TestElemAlgorithmWithViews) now executes correctly
in true multi-threaded mode (OpenMP). It uses the SharedMemView
construct that Christian had prototyped. Unfortunately this means
that it can not use the loop-encapsulation mechanism outlined in
recent slides.
A new version of the element-algorithm has now been added
(TestElementAlgorithmWithTemplate) which uses a templated kernel …

Further refactoring and correcting of the elem-alg unit-tests.

---

unit_tests/UnitTestBasicKokkos.C
unit_tests/UnitTestKokkosViews.C

The algorithm-tests in UnitTestKokkosViews.C don't run on GPU, due
to use of std::vectors, and use of MasterElements which have host-only
functions. But all unit-tests now build for cuda and the kokkos
unit-tests in UnitTestBasicKokkos.C run on cuda/GPU.

Fix unit-tests so they build on nvidia/cuda.

---

src/Realm.C
src/overset/OversetManager.C

The newer stk::mesh::create_exposed_block_boundary_sides is more
robust than skin_mesh, correctly handles a mesh which caused
skin_mesh to issue errors/warnings.

Replace old stk::mesh::skin_mesh with newer stk capability.

---

include/AlgTraits.h
include/HeatCondEquationSystem.h
include/ScalarDiffElemSuppAlg.h
include/ScalarDiffFemSuppAlg.h
include/SupplementalAlgorithmBuilder.h
include/SupplementalAlgorithmBuilderLog.h
include/user_functions/SteadyThermal3dContactSrcElemSuppAlg.h
src/HeatCondEquationSystem.C
src/ScalarDiffElemSuppAlg.C
src/ScalarDiffFemSuppAlg.C
src/SupplementalAlgorithmBuilderLog.C
src/user_functions/SteadyThermal3dContactSrcElemSuppAlg.C

Cleans up some of the logic around building the new templated supplemental algorithm.
* Need to add a "name" to the supplemental algorithm to use the builder function.  The name is what the user will specify in the input file to activate the supplemental algorithm.
* Logs the name of whatever supplemental algorithm that is built (or might be built) by the builder.  So we can output a list of available supplemental algorithms for a particular physics type.

Add a supplemental algorithm builder function

---

include/ElemDataRequests.h
include/ScratchViews.h
src/ElemDataRequests.C
src/ScalarDiffElemSuppAlg.C
src/ScratchViews.C
src/user_functions/SteadyThermal3dContactSrcElemSuppAlg.C
unit_tests/UnitTestElemSuppAlg.C
unit_tests/UnitTestKokkosUtils.h
unit_tests/UnitTestSuppAlgDataSharing.C
unit_tests/UnitTestUtils.h

1. No longer hold 3 arrays of views, each of length num-fields.
Now just hold 1 array of views. Still of length num-fields for now.
2. Change ElemDataRequests::add_gathered_nodal_field to now take
'scalarsPerNode' in addition to the field.
When scalarsPerNode is 1, it will create a 1D scratch-view of length
nodes-per-element. When scalarsPerNode is greater than 1, it will
create a 2D scratch-view with dimensions (nodes-per-element , scalarsPerNode).
This change allows for error-checking to make sure a given gathered
field is requested with consistent dimensions.
This change also allows us to avoid internally calling the
stk::mesh::FieldBase::max_size method.
The functions for retrieving the scratch views are still named
get_scratch_view_1D/2D/3D/4D. The names must be different because
the …

Incremental improvement to supp-alg data-sharing mechanism.

---

include/TpetraLinearSystem.h
src/TpetraLinearSystem.C

1. Moved globally-owned graph construction from
beginLinearSystemConstruction to finalizedLinearSystem (in preparation
for future refactoring of the graph construction process to use
exact profile information for a static graph).
2. Made lookup_myLID method take a const char* instead of a
const std::string& for a debugging string. Passing a string-literal
to a const std::string& causes a std::string construction, which was
sticking up on a profile.
3. Made addConnections take a pointer and length instead of a
std::vector. In many cases there is no need to construct and fill
a std::vector to pass in, when the data being passed is directly
available in a pointer. (i.e., no need to copy). Some cases still
require a copy, but those work just as well passing vector.data() and
size.
4. Clean up …

Minor cleanups and optimizations in TpetraLinearSystem.

---

include/EquationSystem.h
include/HeatCondEquationSystem.h
src/EnthalpyEquationSystem.C
src/EquationSystem.C
src/HeatCondEquationSystem.C
src/LowMachEquationSystem.C
src/MassFractionEquationSystem.C
src/MixtureFractionEquationSystem.C
src/SpecificDissipationRateEquationSystem.C
src/TurbKineticEnergyEquationSystem.C

Move methods from HeatCondEquationSystem so that other EQS can use it.
In preparation for moving Continuity and Momentum SupplementalAlgorithms to the new kokkos-based `AssembleElemSolverAlgorithm`
@rcknaus: Stefan said he wanted you to look at this.

Promote SuppAlg reporting methods to EquationSystem

---

src/LowMachEquationSystem.C

The logic to handle consolidated SuppAlg + Nodal Src Algs + CMM for
hybrid meshes is not correctly implemented. In order to simplify the
logic, and focus on testing consolidated Alg homogeneous kernel design,
the consolidated element Src algs cannot be used together with Nodal Src
Algs. This restriction can be relaxed in future once the homogenous
kernel design has been accepted as the final design.
Fixes #84

Fix logic-error for consolidated SuppAlg in MomEQS

---

include/EquationSystem.h
src/EnthalpyEquationSystem.C
src/EquationSystem.C
src/LowMachEquationSystem.C
src/MassFractionEquationSystem.C
src/MixtureFractionEquationSystem.C
src/SpecificDissipationRateEquationSystem.C
src/TurbKineticEnergyEquationSystem.C

Current code base has a bug where the `useCMM` flag is not set correctly when multiple parts are registered to the interior algorithm. This caused both the element mass SuppAlg as well as the nodal time derivative terms were activated. This pull-request fixes that issue. 
@spdomin: This pull request does not optimize the issue where Nodal Alg Driver is still created when there are zero SuppAlgs requested. That will come in a separate pull request. 
See #84 for discussion.

Fix EQS logic so that nodal time derivative term is not added when CMM is activated

---

src/SurfaceForceAndMomentAlgorithm.C
src/SurfaceForceAndMomentWallFunctionAlgorithm.C

`Fxz` should be `Fvz` and the output precision width was causing columns of data to fuse
together, leading to something like the attached screenshot.
This may have to be changed in other files? Maybe we should consider a "global" value for this?

Fixed minor typo and changed output precision width.

---

include/Enums.h
src/ComputeLowReynoldsSDRWallAlgorithm.C
src/SolutionOptions.C
src/SurfaceForceAndMomentAlgorithm.C

NASA's description of the BC for the Menter SST model includes a wall
factor of 10. The wall factor is now exposed to the user as a
parameter.

Adding SDRWallFactor as a parameter so BC can be matched to NASA.

---

nalu.C

The try/catch just causes the program to terminate with a less informative error message than not catching it would.
Case: an extra space added in front of one of the solution options.
Old behavior: 
>
> terminate called after throwing an instance of 'std::runtime_error'  
>  what():  parser error Realms::load
>
New behavior:
>
>terminate called after throwing an instance of 'YAML::ParserException'
>  what():  yaml-cpp: error at line 108, column 10: end of sequence not found
>

Print the more informative, default YAML error message for parse errors

---

include/ScratchViews.h
src/AssembleElemSolverAlgorithm.C
src/ScratchViews.C
unit_tests/UnitTestSuppAlgDataSharing.C

Fix segfault by adding 64 extra bytes to account for any alignment
requirements.

Remove factor of 2 in numBytes calculation for ScratchViews

---

include/LinearSolverTypes.h
include/TpetraLinearSystem.h
src/TpetraLinearSystem.C

Initialization is improved by computing an array of row-lengths
to give to CrsGraph at construction (instead of the previous hard-
coded '8').
Assembly is improved by calling sumIntoValues on the local kokkos
matrix obtained from the Tpetra::CrsMatrix object via getLocalMatrix().
Previously, we were calling Tpetra::CrsMatrix::sumIntoLocalValues.
Some other optimizations are done, such as reducing the number of calls to
CrsGraph::insertGlobalIndices by trying to process more of the
column-indices for a given row, rather than making separate calls
for each row-column pair.
Overall, these changes appear to speed up the uqSlidingMeshDG test
by ~10%. The cube6M problem running on serrano is sped up by about
an 8-10% improvement in the 'init' timer. The performance of the …

Improve TpetraLinearSystem initialization and assembly.

---

include/ABLForcingAlgorithm.h
src/ABLForcingAlgorithm.C

Minor update to output `computed` source terms to a file for analysis and to be used as input in prescribed source term runs.

ABLForcing: Output computed source terms for analysis/reuse

---

src/ABLForcingAlgorithm.C

`get_if_present` was used incorrectly in `ABLForcing` class. This caused optional entries that were initialized in the constructor to be reset if the user did not provide in the input file. 
Fixes the failure of RTest mentioned in  #110 
@gantech , @skennon10 FYI.

ABLForcing: Fix usage of `get_if_present` when parsing optional values.

---

include/OutputInfo.h
src/OutputInfo.C
src/Realm.C

The changes are in Realm.C and OutputInfo.C, and OutputInfo.h. The build will succeed as long as you are building against the Trilinos master branch and you set the following flag in your Trilinos build:
-DTrilinos_ENABLE_SEACASIoss:BOOL=ON
ParaView Catalyst will only be active when an "output" block in a Nalu input deck contains a "catalyst_file_name" command. It is also necessary to build the ParaView Catalyst adapter against an install of ParaView and set an environment variable to point to the install location. We will need to update the Nalu build instructions to show these details. 
The environment variable is called CATALYST_ADAPTER_INSTALL_DIR. It should be set to the root of the install directory for the Catalyst adapter.

Enable paraview catalyst

---

build/do-configTrilinos_debug
build/do-configTrilinos_release

Enable the Seacas IOSS module in Trilinos build to produce
the Iovs library necessary for linking Catalyst.

Modify Trilinos configure scripts for Catalyst.

---

unit_tests/UnitTestHexMasterElements.C

Fix the second array index for-loop in check_interpolation and
check_derivatives methods.
Fixes #68.

Fix segfault on OS X + LLVM for MasterElementHexSerial tests

---

include/NaluParsing.h
src/NaluParsing.C
src/SolutionOptions.C

Case: a user says
`turbulence_model: smag`
Old behavior: code would run with a laminar model. (Incorrect name).
New behavior: throws
`` 
what():  Turbulence model `smag' not implemented.
Available turbulence models are `laminar', `ksgs', `smagorinsky', `wale', `sst', `sst_des'
``

Add input checking to turbulence model specification

---

include/ElemDataRequests.h
include/ScratchViews.h
src/AssembleElemSolverAlgorithm.C
src/ContinuityAdvElemKernel.C
src/ContinuityMassElemKernel.C
src/ElemDataRequests.C
src/MomentumAdvDiffElemKernel.C
src/MomentumBuoyancySrcElemKernel.C
src/MomentumMassElemKernel.C
src/ScalarAdvDiffElemKernel.C
src/ScalarDiffElemKernel.C
src/ScalarMassElemKernel.C
src/ScalarUpwAdvDiffElemKernel.C
src/ScratchViews.C
src/nso/MomentumNSOElemKernel.C
src/nso/MomentumNSOKeElemKernel.C
src/nso/MomentumNSOSijElemKernel.C
src/nso/ScalarNSOElemKernel.C
src/user_functions/SteadyThermal3dContactSrcElemKernel.C
unit_tests/UnitTestElemSuppAlg.C
unit_tests/UnitTestSuppAlgDataSharing.C
unit_tests/kernels/UnitTestKernelUtils.C
unit_tests/kernels/UnitTestKernelUtils.h

- Refactor Scratchviews to handle current and model coordinates and
the relationship with master element data.
- Remove coordinates from fill_pre_req_data and use appropriate
coordinates registered by the user to populate MasterElement view
arrays.
- Extend master element data registration and retrieval methods to
indicate the coordinates field used to compute the relevant data.
- Update all Kernels and UnitTests to adhere to new ScratchViews
interface.

Kokkos ScratchViews interface update

---

build/do-configTrilinos_debug
build/do-configTrilinos_release

This is a pre-requisite for doing any simd work in nalu.
@spdomin what is the process, apart from changing these do-configTrilinos* files, for getting a configuration change pushed out across the nalu project?

Activate stk-simd support in Trilinos configuration.

---

reg_tests/CTestList.cmake

@spdomin @jrood-nrel Changing CTest script to use the variables declared in toplevel `CMakeLists.txt`

Fix CTest to enable testing on debug build executable names

---

include/AssembleMomentumEdgeABLWallFunctionSolverAlgorithm.h
include/AssembleMomentumEdgeWallFunctionSolverAlgorithm.h
include/AssembleMomentumElemABLWallFunctionSolverAlgorithm.h
include/AssembleMomentumElemWallFunctionSolverAlgorithm.h
src/AssembleMomentumEdgeABLWallFunctionSolverAlgorithm.C
src/AssembleMomentumEdgeWallFunctionSolverAlgoirthm.C
src/AssembleMomentumElemABLWallFunctionSolverAlgorithm.C
src/AssembleMomentumElemWallFunctionSolverAlgoirthm.C
src/LowMachEquationSystem.C

* convert standard wall function flavor
* convert ABL wall function flavor
Notes:
a) The motivation of this push is to increment towards allowing the
element-based scheme to assemble the pressure gradient term within
interior and boundary contributions rather than applying a nodal source
term in time. With this commit, all adv/diff edge- and element-based matrix
contributions are in seperate implementations. The next step will be to add
a total advection term to Elem-based algoirthms, i.e., rho*ui*uj + p*del_ij

Transition wall function to a pure edge- or element-based implementation

---

src/ContinuityAdvElemKernel.C
unit_tests/kernels/UnitTestContinuityAdvElem.C

- The logic for `shift_cvfem_poisson = true` was not reflected correctly
in advection kernel and caused a segfault accessing ME views that
weren't registered in construction phase.
- Added a unit test to test this flag. 
Proposed fix for #143.

Fix segfault in Continuity Advection Kernel

---

src/master_element/MasterElement.C

Face 3 made in recent STK bug fix. Face 3 node ordering changed from
(3,0,4) -> (0,4,3).

Modified PyrSCS node and face mappings to be consistent with changes to

---

src/master_element/MasterElement.C

As we wait and learn more about shifting gradient_operators for wedges and, especially, pyramids, we know that Pyr5::Tri3 faces at exposed surfaces have a zero detJ at the apex node. 
This pull request manages this as we learn how to proceed.

Add fix for detJ at Pyr5SCS::shifted_face_grad_op

---

include/master_element/MasterElement.h
src/master_element/MasterElement.C
unit_tests/UnitTestHexMasterElements.C

I added the HexSCS new calls. I still need to convert HexSCV, however, that should only be a few methods.
At present, I do not have a unit test approach for these new methods. Will work with @sayerhs tomorrow on that.
@alanw0 can use this for unit testing or in crafting the new Solver interface. As noted, anything with SCV_VOLUME will not yet work. That means source terms.
@rcknaus can also massage the newly defined call signatures for grad_op, determinant, etc.

WIP Master element HexSCS SIMD

---

unit_tests/UnitTestHexElementPromotion.C
unit_tests/UnitTestQuadElementPromotion.C

This should fix the errors involving the change of STK header file locations in Trilinos once the fix in https://github.com/trilinos/Trilinos/issues/1433 is merged. Probably doesn't make much difference if we merge this PR now or after the Trilinos fix is merged.

Update header file locations of STK fixtures.

---

include/Enums.h
include/FixPressureAtNodeAlgorithm.h
include/FixPressureAtNodeInfo.h
include/LinearSystem.h
include/SolutionOptions.h
include/TpetraLinearSystem.h
src/FixPressureAtNodeAlgorithm.C
src/LowMachEquationSystem.C
src/SolutionOptions.C
src/TpetraLinearSystem.C

Allow user to fix the reference pressure at an arbitrary location within
the computational domain during simulations.
This capability is important for the pressure Poisson solve during
ABL precursor simulations where the side boundaries are usually set to
periodic and the top boundary is specified with a symmetry BC to allow
the flow to adjust naturally when targeting a specified wind
speed/direction at hub height.

Fix reference pressure at an interior node

---

src/SpecificDissipationRateSSTNodeSourceSuppAlg.C
unit_tests/algorithms/UnitTestSSTAlgorithms.C

Respect the user's choice of tkeProdLimitRatio in SDR source.

---

unit_tests/UnitTestFieldUtils.C
unit_tests/UnitTestFieldUtils.h
unit_tests/UnitTestUtils.C
unit_tests/UnitTestUtils.h
unit_tests/algorithms/UnitTestAlgorithm.C
unit_tests/algorithms/UnitTestAlgorithm.h
unit_tests/algorithms/UnitTestAlgorithmUtils.h
unit_tests/algorithms/UnitTestSSTAlgorithms.C

The turbulence unit tests were not thread-safe so `export OMP_NUM_THREADS=2; ctest -R unit` failed with a segfault. This commit makes the turbulence unit tests thread-safe.

Making the turbulence tests threadsafe.

---

docs/CMakeLists.txt
docs/source/theory/lowMachNumberDerivation.rst
docs/source/theory/supportedEquationSet.rst

- New target `sphinx-pdf` that calls the `latexpdf` sphinx generator
to create a Nalu.pdf file.
- Fix RST declarations of some equations that weren't converted to
latex properly. Disabled automated wrapping and manually created
the equations in latex format to get the desired layout.
- Also added a `sphinx-html` target to bypass doxygen runs - useful
looking a HTML docs while working on RST files.

Nalu Docs: Create CMake rule for generating PDF documentation

---

src/TpetraLinearSystem.C

replacing values.
We use replaceValues for applying dirichlet boundary conditions.
We have been given guidance from the Trilinos folks to prefer using
the Kokkos local matrix rather than the Tpetra::CrsMatrix for
modifying matrix values.

Use local kokkos matrix API instead of Tpetra::CrsMatrix API for

---

include/EquationSystem.h
include/LinearSystem.h
include/TpetraLinearSystem.h
src/EnthalpyEquationSystem.C
src/EquationSystem.C
src/HeatCondEquationSystem.C
src/LinearSystem.C
src/LowMachEquationSystem.C
src/MassFractionEquationSystem.C
src/MixtureFractionEquationSystem.C
src/ProjectedNodalGradientEquationSystem.C
src/SpecificDissipationRateEquationSystem.C
src/TpetraLinearSystem.C
src/TurbKineticEnergyEquationSystem.C
src/mesh_motion/MeshDisplacementEquationSystem.C
src/pmr/RadiativeTransportEquationSystem.C
unit_tests/UnitTestHelperObjects.h
unit_tests/UnitTestLinearSystem.h

There is a clash over names of equation systems. The EquationSystem
is provided an internal name when created. However, later, the
load() step overides this name with a user suplied value.
Consider the following:
LowMachEQS
name: myLowMach
MixtureFractionEQS
name: myZ
TurbKinEnerEQS
name: myTke
Each of the user supplied names are provided above. LowMach creates momentum
and continuity with name_ set to internally suplied names, e.h. "MomEQS"
and "ContEQS". MixFrac and TKE will use also use an internal name, e.g.,
"MixFracEQS", to create the EQS and provide this name to LinSys. However,
after the load() for the equation system input block, the name_ will
be reset to the user supplied name, e.g., "myZ". Therefore,
the name that LinSys uses to look up the EQS will be "MixFracEQS". The eqSys_ …

Bug fix for #183 and #184

---

include/LinearSystem.h
include/SolverAlgorithm.h
include/TpetraLinearSystem.h
src/AssembleElemSolverAlgorithm.C
src/SolverAlgorithm.C
src/TpetraLinearSystem.C
unit_tests/UnitTestLinearSystem.h

* Sorts the local column indices on a per-element basis.  This allows us to search for offsets and modify matrix values in just one pass for a particular element being summed into the linear system.  
* Shows a good speed-up on small tests problems, especially with intel compilers.  I plan to---but have yet to---get performance data on a large scale problem.

Use custom sumInto function instead of Tpetra call

---

include/CopyAndInterleave.h
include/ScratchViews.h
src/AssembleElemSolverAlgorithm.C
unit_tests/UnitTestKokkosME.h
unit_tests/kernels/UnitTestKernelUtils.h

vtune showed that copy/interleave, together with extract_vector_lane,
was occupying about 17% of AssembleElemSolverAlgorithm::execute on
KNL, for the momentum-kernels unit test. The changes in this commit
bring that down to about 6%.

Low level optimizations to the copy/interleave code supporting simd.

---

reg_tests/CTestList.cmake
reg_tests/test_files/ablForcingEdge/ablForcingEdge.i
reg_tests/test_files/mixedTetPipe/mixedTetPipe.i
reg_tests/test_files/steadyTaylorVortex/steadyTaylorVortex.i

It turns out the catalyst code additions were broken and made many existing tests run blank `sh -c` commands, so they weren't running anything and succeeding by default. This pull request reinstates the old function for adding regression tests and adds a separate function for adding tests with catalyst capability.
I'm going to merge this as soon as I verify it runs the tests correctly.
@tjotaha  Can you check if this still runs your tests like you expect?

Fixing many broken tests

---

include/KernelBuilder.h
src/HeatCondEquationSystem.C

* adds a new method "build_fem_kernel_if_requested" that only instantiates topologies that have FEM implementations (only Hex8, currently).
* Addresses Issue #217

Add FEM kernel builder

---

src/master_element/Tri32DCVFEM.C

Variable length arrays are non-standard and in this case it was not needed.

Change VLA to simple Scalar.  #220

---

include/Kernel.h
include/ScalarDiffFemKernel.h
src/ScalarDiffFemKernel.C

* Added new get_fem_shape_fcn_data()
Notes:
a) Not sure if this is the best way. I am following the pattern already
coded and wonder if there is a better way to do all of this. Let me know
in the review:)
b) The original call to scs sized by the scsIp and npe; this probably resuted in a memory
overrun.

Add specialized fem-based methods for kernel shape functions extraction

---

src/NonConformalInfo.C

* Make sure to clear the opposing vector of possible candidate
faces for each dgInfo object.
* see: https://jira.exascaleproject.org/browse/ADSE07-248

Memory bloat in bloating algorithm bug fix

---

include/Realm.h
src/Realm.C
src/element_promotion/PromotedElementIO.C

* Changes the postprocessor target names to the corrected super element part name for promoted meshes.
* For outputting surface fields like tau_wall, I'll need to implement a sideset writer for the sub-divided high order elements.

Change target names for postprocessing with promoted meshes

---

include/Realm.h
include/TpetraLinearSystem.h
src/Realm.C
src/TpetraLinearSystem.C
unit_tests/UnitTestGetDofStatus.C

Made the body of getDofStatus into a free-function that is called
by the TpetraLinearSystem class member. That way it can also be
called by unit-tests.
These first unit-tests are very basic, only checking owned and
shared. It will be useful to add slightly more sophisticated tests
to nail down getDofStatus behavior for ghosted, periodic and
other dof flavors.

Initial simple unit-tests of the getDofStatus function.

---

src/EquationSystem.C
src/LinearSolver.C

Fixes #238. Previously, the preconditioner timer data was lost when the
LinearSolver instance was destroyed within reinitialize_linear_system resulting
in incorrect reporting of timerPrecond_ and timerSolve_.

Fix error in preconditioner timer calculations with system reinitialization

---

src/LinearSolverConfig.C

This commit causes Belos to print the Krylov residual history in a simpler format, similar to Aztec (for those of you who remember that package).  The default Belos output can be confusing and prints more information than we'd typically want to see.  Here's a before/after example:
**before**
```
Belos::StatusTestGeneralOutput: Failed
(Num calls,Mod test,State test): (1, 1, Passed Failed Undefined)
Failed.......OR Combination -> 
OK...........Number of Iterations = 0 < 50
Unconverged..(2-Norm Res Vec) / (2-Norm Prec Res0)
residual [ 0 ] = 1 > 1e-05
Belos::StatusTestGeneralOutput: Failed
(Num calls,Mod test,State test): (2, 1, Passed Failed Undefined)
Failed.......OR Combination -> 
OK...........Number of Iterations = 1 < 50
Unconverged..(2-Norm Res Vec) / (2-Norm Prec Res0)
residual [ 0 ] …
```

Improve the Belos output in Nalu

---

CMakeLists.txt

I think it's time we uptick the required CMake to 3.1 and close #168 .

Require cmake version 3.1 or greater

---

src/master_element/Wed6CVFEM.C

* note sure why we have duplicated sideNodeOrdinal - a duplicate
of ipNodeMap. In this case, the later datastructure was fine: 0,2,1.

Fix #246; Wedge6SCS::ipNodeMap_

---

include/user_functions/OneTwoTenVelocityAuxFunction.h
src/LowMachEquationSystem.C
src/SolutionNormPostProcessing.C
src/user_functions/OneTwoTenVelocityAuxFunction.C

* 1x2x10 is a developing verification test. Will push the mesh files
if we feel that this is required.
Notes:
a) project is non-wind related, although the 1x2x10 might become
an A2e open BC verification test

Add 1x2x10 analytical function for IC and solution norms

---

include/LinearSolver.h
include/LinearSolverConfig.h
include/Realm.h
src/LinearSolver.C
src/LinearSolverConfig.C
src/Realm.C
src/TpetraLinearSystem.C

For ABL simulations, we have been using different tolerance settings for the linear solvers, i.e., use a lax tolerance normally except for the final outer iteration when a tighter tolerance level is chosen. This pull request implements the necessary modifications to allow this. 
```
linear_solvers:
- name: solve_scalar
type: tpetra
method: gmres
preconditioner: sgs
tolerance: 1e-3
final_tolerance: 1e-6
max_iterations: 75
kspace: 75
output_level: 0
- name: solve_cont
type: tpetra
method: gmres
preconditioner: muelu
tolerance: 1e-3
final_tolerance: 1e-6
max_iterations: 75
kspace: 75
output_level: 0
recompute_preconditioner: no
```
Preserves backward compatibility by default to `tolerance` if `final_tolerance` is not provided in the input file.

Allow different tolerance levels for predictor and final corrector iters

---

include/LinearSolver.h
include/LinearSolverConfig.h
include/Realm.h
src/LinearSolver.C
src/LinearSolverConfig.C
src/Realm.C
src/TpetraLinearSystem.C

Add an option in `linear_solvers` section to allow user to specify
linear solver convergence tolerance settings for the final and
prior outer iterations.
This commit fixes the error seen in certain regression tests after a
previous attempt at implementing this feature in pull request #256. Please
see the discussion in #256 for @spdomin's admonitions on using this feature,
particularly its interactions with the convergence tolerance setting in EQS
inputs.

Allow different tolerance settings for final/non-final outer iters

---

include/nso/MomentumNSOElemKernel.h
include/nso/MomentumNSOSijElemKernel.h
include/nso/ScalarNSOKeElemKernel.h
src/nso/MomentumNSOElemKernel.C
src/nso/MomentumNSOSijElemKernel.C

As per Srini's request, I have taken a shot at cleaning up, as a first step, NSO copyright.
All of these cases below are the "easy" type in which a copyright clause has been copy/pasted in error. Code converted as part of the large re-factor has been left alone as we need to discuss this as a team.
The pedigree of the code is below. In one case, a later file rename caused a copyright change.
Author: Stefan P. Domino <spdomin@sandia.gov>  2017-03-01 16:06:44
Committer: Stefan P. Domino <spdomin@sandia.gov>  2017-03-01 16:06:44
Parent: a89639787541783a735eff17c3acf27396ca089d (Increasing test timeout values, and disabling non-uniform tests for the moment.)
Child:  80043a4a1e79ed416b7639e46a44748c50786bff (Convert MomAdvDiffSuppAlg to the new infrastructure)
Branches: copyFixNSO, master, …

Copy fix NSO; simple

---

include/ContinuityAdvElemKernel.h
include/ContinuityMassElemKernel.h
include/Kernel.h
include/MomentumBuoyancyBoussinesqSrcElemKernel.h
include/MomentumBuoyancySrcElemKernel.h
include/MomentumMassElemKernel.h
include/ScalarDiffElemKernel.h
include/ScalarDiffFemKernel.h
include/ScalarMassElemKernel.h
include/master_element/Wed6CVFEM.h
include/nso/MomentumNSOKeElemKernel.h
include/nso/ScalarNSOElemKernel.h
include/user_functions/SteadyThermal3dContactSrcElemKernel.h
src/ContinuityAdvElemKernel.C
src/ContinuityMassElemKernel.C
src/MomentumBuoyancyBoussinesqSrcElemKernel.C
src/MomentumBuoyancySrcElemKernel.C
src/MomentumMassElemKernel.C
src/ScalarDiffElemKernel.C
src/ScalarDiffFemKernel.C
src/ScalarMassElemKernel.C
src/master_element/Wed6CVFEM.C
src/nso/MomentumNSOKeElemKernel.C
src/nso/ScalarNSOElemKernel.C
src/user_functions/SteadyThermal3dContactSrcElemKernel.C

Based on discussions with SNL legal, reverting copyright notices on
Kernel files which were originally implemented as SupplementalAlgorithms
with the only changes introduced being conversion to Kokkos based data
structures.

Fix copyright notices on Kernel files

---

unit_tests/UnitTestABLWallFunction.C
unit_tests/UnitTestLinearSystem.h
unit_tests/UnitTestUtils.h

* ABLWallFunction.compute_abl_utau tests the iterative solve for the
wall friction velocity utau, for the case of neutral, unstable, and
stable temperature stratification.
* ABLWallFunctionHex8ElementWithBCFields.abl_wall_function_elem_alg_rhs
tests the element algorithm assembly of the rhs vector for one face of a hex8
element.
* ABLWallFunctionHex8ElementWithBCFields.abl_wall_function_edge_alg_rhs
tests the edge algorithm assembly of the rhs vector for one face of a hex8
element.
* The sumInto method of the TestLinearSystem class for the case of
std::vector rhs and lhs arguments was implemented, in order to
save off the rhs values from the wall function algorithm and test
them against pre-calculated values.
* To facilitate the algorithm tests, a test fixture was written that
creates a …

Added three unit tests for the abl_wall_function boundary condition.

---

docs/source/theory/boundaryConditions.rst
docs/source/user/nalu_run/nalu_inp.rst

* Removed description of the Moeng wall function from the theory manual,
since this is not implemented in master.
* Added more detail on the ABL wall function input parameters to the
user manual.

Documentation cleanup for ABL wall function

---

src/NonConformalInfo.C

Push back id of opposing face, rather than theBox, to the
opposing-faces data.
Also set the canReuse_ flag if all needed opposing faces are
in the 'old' opposing face data.

Fix a minor bug in the non-conformal stencil-bloating logic.

---

src/ShearStressTransportEquationSystem.C

Unless there is a good reason for the way it was, I think this is a typo. This minor typo does not affect the unit tests or regressions.

Minor typo fix: Grab SDR at state NP1 not N.

---

CMakeLists.txt
docs/source/user/build_manually.rst
include/FieldTypeDef.h
include/HypreDirectSolver.h
include/HypreLinearSystem.h
include/Realm.h
include/XSDKHypreInterface.h
src/HypreDirectSolver.C
src/HypreLinearSystem.C
src/Realm.C

- Use HYPRE_Int type throughout to match datatypes used by HYPRE within Nalu's
HYPRE interface. Add appropriate checks to ensure that the HYPRE library can
support the size of linear systems required for problem sizes (`> O(~1
billion)`).
- Update CMakeLists to check and warn users if HYPRE's 64-bit support is not
enabled.
- Update HYPRE build documentation with additional instructions to build HYPRE
with 64-bit integer support.

HYPRE: Add 64-bit integer support for Hypre interface.

---

include/TpetraLinearSystem.h
src/TpetraLinearSystem.C

Store a reference to the local-matrix and local-rhs objects
instead of getting them during every call to sumInto. The
reference is refreshed during each call to finalizeLinearSystem
so that it isn't invalidated by mesh motion etc.

Optimization in sumInto, saves ~10% of assembly time

---

include/AssembleElemSolverAlgorithm.h
include/CopyAndInterleave.h
include/ElemDataRequests.h
include/KernelBuilder.h
include/ScratchViews.h
src/AssembleElemSolverAlgorithm.C
src/ScratchViews.C
unit_tests/UnitTestElemSuppAlg.C
unit_tests/UnitTestHelperObjects.h
unit_tests/UnitTestKokkosME.h
unit_tests/UnitTestSuppAlgDataSharing.C
unit_tests/kernels/UnitTestKernelUtils.C

Removed topo argument from ScratchViews and related functions,
and from AssembleElemSolverAlgorithm. Also generalized
entity-rank and nodes-per-entity in AssembleElemSolverAlgorithm.
There's still more to do, but this is a good start.

Some cleanup in ScratchViews and AssembleElemSolverAlgorithm.

---

include/ElemDataRequests.h
include/ScratchViews.h
src/ElemDataRequests.C
src/ScratchViews.C
unit_tests/UnitTestHelperObjects.h
unit_tests/UnitTestUtils.h
unit_tests/kernels/UnitTestFaceBasic.C
unit_tests/kernels/UnitTestFaceElemBasic.C
unit_tests/kernels/UnitTestKernelUtils.h

In unit_tests/kernels/UnitTestFaceElemBasic.C see the
class TestFaceElemAlgorithm, and its method run_face_elem_algorithm.
The run_face_elem_algorithm method uses a similar looping structure
to that used in AssembleElemSolverAlgorithm, but manages two
instances of the ElemDataRequests and ScratchViews objects, specifically
for face data and element data.
Jointly with Stefan and Robert, plumbed another master-element ('meFC')
into the ElemDataRequest and ScratchViews objects. We debated whether to
add the new master-element into those objects or to split those objects
such that a given instance would only hold the needed master-elements.
For now at least, we just added a new master-element into the existing
classes.
Still some issues to be worked out:
- Would face-elem-algorithm instances …

Unit-test to prototype a face-element algorithm.

---

include/AssembleElemSolverAlgorithm.h
include/SharedMemData.h
src/AssembleElemSolverAlgorithm.C
unit_tests/UnitTestKokkosME.C
unit_tests/UnitTestKokkosME.h

In order to be consistent with AssembleFaceElemSolverAlgorithm
and to facilitate unit-testing of kernels and master-elements
without duplicating the mesh loop and scratch-view management.

Add run_algorithm template to AssembleElemSolverAlgorithm

---

docs/source/developer/testing.rst
docs/source/user/build_manually.rst

This updates the YAML instructions in the documentation to recommend using a specific commit or the master branch of YAML-CPP. Addressing #309 .

Upating YAML instructions in documentation

---

include/kernel/TurbKineticEnergyKsgsSrcElemKernel.h
src/kernel/TurbKineticEnergyKsgsSrcElemKernel.C

When I tried to use the source term defined in TurbKineticEnergyKsgsSrcElemKernel (this is not the DesignOrder one), I got an error when trying to add the master element call to SCV_VOLUME.  I believe this was due to the coordinates field not being defined, which this pull request resolves.

Bug fix for TurbKinEne Ksgs kernel, was missing coordinates_ definition.

---

include/LinearSolverTypes.h

Recent updates to Tpetra in Trilinos removed the classic template parameter for
Vector and MultiVector. This caused build errors when compiling Nalu with the
latest Trilinos develop branch. This commit fixes this issue.
Fixes #333.

Fix declaration of Tpetra::MultiVector and Tpetra::Vector in Nalu

---

include/Realm.h
include/overset/OversetManagerSTK.h
include/overset/TiogaBlock.h
include/overset/TiogaSTKIface.h
reg_tests/test_files/overset/overset.i
reg_tests/test_files/oversetSphereTIOGA/oversetSphereTIOGA.i
src/Realm.C
src/overset/OversetManagerSTK.C
src/overset/OversetManagerTIOGA.C
src/overset/TiogaBlock.C
src/overset/TiogaSTKIface.C

Fixes error when the user enables "check_for_missing_bcs" in the input
file and overset BC is active. The fix adds overset side_set targets to
the realm.bcPartVec_ so that enforce_bc_on_exposed_faces will skip these
parts during the BC check step.
Updated two regression tests to provide coverage for this ability.

Account for overset BC parts with check_for_missing_bcs

---

include/AveragingInfo.h
include/TurbulenceAveragingPostProcessing.h
reg_tests/test_files/heliumPlume/heliumPlume.i
src/AveragingInfo.C
src/TurbulenceAveragingPostProcessing.C

* HIT and T-G sims require mean ke over the domain. This simple
commit promotes what I have been maintaining under LowMachEQS for
purposes of SNL NGS project.
* helium plume test modified to exercise the new post processing. Here,
the volume matches.
* fixed a trivial name while I am here
* add inactive selector as per RCK review
Notes:
a) In my -pi:pi^3 domain with triple peridocity, nodally iterating
provides a "periodic" volume as apposed to only the volume encompassed
by the domain. As such, the new postprocessing is actually more accurate
- at least for low-order.

Add mean resolved ke to turbulence averaging

---

include/BcAlgTraits.h
include/BuildTemplates.h
include/kernel/KernelBuilder.h
include/kernel/MomentumAdvDiffElemKernel.h
include/kernel/MomentumOpenAdvDiffElemKernel.h
include/pmr/RadTransWallElemKernel.h
src/kernel/KernelBuilderLog.C
src/pmr/RadTransWallElemKernel.C
src/pmr/RadiativeTransportEquationSystem.C

* add new element types to BcAlgTraits
* add face only instantiation
* add RadTransWallElemKernel
* add kernel builder for face algs
* remove Built Supplemental Algs in favor of Kernels
* build template for face_bc
Notes:
a) good news, no diffs noted (concentic and inputFire)
b) ready to deploy for all other face-only bc algorithms.
c) sadly, AssembleRadTransWall is still there for edge-based only
d) new design looks nice and clean.

First exposed face bc algorithm (consolidated)

---

src/TurbulenceAveragingPostProcessing.C

* The selector needs to include !slave_nodes... Now, volume is matching
the previous approach.

Add mean resolved ke to turbulence averaging; final bug fix

---

include/kernel/MomentumOpenAdvDiffElemKernel.h
include/kernel/MomentumSymmetryElemKernel.h
include/kernel/ScalarOpenAdvElemKernel.h
src/kernel/MomentumOpenAdvDiffElemKernel.C
src/kernel/MomentumSymmetryElemKernel.C
src/kernel/ScalarOpenAdvElemKernel.C
unit_tests/UnitTestUtils.h
unit_tests/kernels/UnitTestFaceElemBasic.C

* coded advection-based scalar element kernel
* realized nearest node was wrong in all face/elem kernels. Resolved
this first in ScalarOpenAdv and then propogated the change to MomentumOpen
and MomentumSymm.
Notes:
a) open is last, however, I think that I will transition back to
executing the full path for Scalar open. At that point, all scalars can
deprecate.
b) the easiest path forward is probably to fully activate ScalarOpen,
MomentumSymm, and, finally, MomentumOpen.

Added scalar open eleme kernel with unit test

---

include/NonConformalInfo.h
src/NonConformalInfo.C

If the search fails to find a match for some elements then
increase the search distance and repeat the search with just
the elements that were not matched.  This will keep the dynamic
search tolerance algorithm from failing if the search tolerance
suddenly needs to be increased by a large factor from one time
step to the next. If after doubling the search tolerance ten times
and there are still points with no match the function then throws
an error.

Add logic to repeat search at non-conformal interfaces.

---

include/AssembleFaceElemSolverAlgorithm.h
unit_tests/kernels/UnitTestFaceElemBasic.C

ordinals in simd groups.
Our master-element and kernel implementations require that within
a simd group, all faces have the same element-ordinal.
Created a unit-test which alters a mesh to ensure at least two faces
with different element-ordinals are in the same bucket, then added
a custom kernel::execute method which checks for different ordinals
in the same simd group. Then put the corrected algorithm looping
in place to make the test pass.

Alter face-element algorithm looping to ensure uniform face-element

---

include/CopyAndInterleave.h
include/master_element/MasterElementHO.h
src/kernel/TurbKineticEnergyKsgsDesignOrderSrcElemKernel.C
src/master_element/MasterElementHO.C
unit_tests/UnitTestHOMasterElements.C

* Addresses #335
* Gets rid of the unused ability to specify sub/super parametric elements for promoted elements.  
* Adds clipping for ip values in design order ksgs, since the interpolation isn't necessarily monotonic

Add SCV grad_op for promoted elements

---

include/kernel/SpecificDissipationRateSSTSrcElemKernel.h
include/kernel/TurbKineticEnergySSTDESSrcElemKernel.h
include/kernel/TurbKineticEnergySSTSrcElemKernel.h
src/SpecificDissipationRateEquationSystem.C
src/TurbKineticEnergyEquationSystem.C
src/kernel/SpecificDissipationRateSSTSrcElemKernel.C
src/kernel/TurbKineticEnergySSTDESSrcElemKernel.C
src/kernel/TurbKineticEnergySSTSrcElemKernel.C
unit_tests/kernels/UnitTestKernelUtils.h
unit_tests/kernels/UnitTestSSTSrcElem.C

Most of the code here has already been reviewed (a while back...) but I finally got around to running a comparison using the current CVFEM implementation and a consolidated implementation that uses the new source kernels. The comparison was done using the NASA wall hump and a sample velocity profile can be seen in this graph. Both implementations predict the same velocity fields (same goes for surface coefficients).
The input files used for the comparison are the following:
- [previous implementation (using SuppAlg)](https://github.com/marchdf/wallHump/blob/master/twod/817x217/wallHump_p1.i)
- [using the new kernels (consolidated approach)](https://github.com/marchdf/wallHump/blob/master/twod/817x217/wallHump_p1_consolidated.i)
Appropriate unit tests were added for the new source kernels.

Added SST source kernels and unit tests.

---

include/AssembleFaceElemSolverAlgorithm.h
include/ComputeMdotElemOpenPenaltyAlgorithm.h
include/LowMachEquationSystem.h
include/SharedMemData.h
include/kernel/ContinuityOpenElemKernel.h
include/kernel/Kernel.h
include/kernel/KernelBuilder.h
include/kernel/MomentumOpenAdvDiffElemKernel.h
include/kernel/MomentumSymmetryElemKernel.h
src/AssembleFaceElemSolverAlgorithm.C
src/ComputeMdotElemOpenPenaltyAlgorithm.C
src/LowMachEquationSystem.C
src/kernel/ContinuityOpenElemKernel.C
src/kernel/MomentumOpenAdvDiffElemKernel.C
src/kernel/MomentumSymmetryElemKernel.C
src/kernel/ScalarOpenAdvElemKernel.C
unit_tests/kernels/UnitTestFaceElemBasic.C

Design-order penalty continuity approach has been established. Time to deprecate
the old (Pbip - Pscs_op) approach.
* This push required a number of plumbing fixes to the former face/element
approach. BC creation is currently automatic. Formerly, symmetry bc
was being created if the lumped_mass and adveciton element source terms
were active. I fixed this to use automatic. Diffs expected as now only
one symmetry kernel will be called:)
* Generalized the face/element kernel creation allowing for
quad4/hex8/pyr5/wedge6 and tri3/tet4/pyr5/wedge6 combinations. Before,
it was only creating quad4/hex8 and tri3/tet4. This covers the full
hybrid element topos.
* Provide elemOrdinal to all face/elem kernels through a new argument. This
resolves the former FIXME #2 in which face_ordinal was hard …

Towards the penalty approach for element-based open.

---

src/master_element/Pyr5CVFEM.C
src/master_element/Wed6CVFEM.C
unit_tests/UnitTestKokkosMEBC.C

* Fixes a bug introduced in the wed/pyr SIMD face_grad_op introduced with https://github.com/NaluCFD/Nalu/commit/6cb74b4abc0e91f2fc2bbb79348c705a7852cd16
* Re-enables SIMD face_grad_op unit test for wed/pyr.  I verified that it passes with intel 17 locally.

Fix and re-enable Wed/Pyr face_grad_op test

---

src/HypreLinearSystem.C

Prior to Hypre v2.14.0, there was no quick way to zero out the entries
in an IJMatrix while preserving the connections. Nalu interface to Hypre
had resorted to destroying and recreating the IJMatrix during the call
to HypreLinearSystem::zeroSystem. This meant that the IJMatrix was
recreated during every outer iteration even if there was no mesh motion.
This overhead is removed by using HYPRE_IJMatrixSetConstantValues to
zero out entries but preserve the matrix structure from previous calls.

Hypre: Use new functions in Hypre API to zero matrix.

---

include/AssembleScalarEigenEdgeSolverAlgorithm.h
include/EigenDecomposition.h
src/AssembleScalarEigenEdgeSolverAlgorithm.C
src/EigenDecomposition.C
unit_tests/UnitTestEigenDecomposition.C

Extracted the eigenvalue decomposition from the AssembleScalarEigenEdgeSolverAlgorithm and created a separate EigenDecomposition class to handle this.  This will allow additional units, such as those involved with the new Hybrid model to have access to the EVD solver.
I also created unit tests for the EVD solvers.  
To test the implementation, I ran the ablNetural reg test and added the below to solution options to force it to invoke the EigenEdgeSolverAlgorithm and verified my solution was unchanged with the included code modifications.
eigenvalue_perturbation: yes
I didn't find any existing unit tests or reg tests that tested AssembleScalarEigenEdgeSolverAlgorithm, if there is one, please let me know and I will run it against that.  Thanks.

Create eigenvalue decomposition as its own class

---

include/TpetraLinearSystem.h
src/TpetraLinearSystem.C

1. Use parameter "compute triangular constants" -> false
To avoid the expense of determining whether the matrix graph is triangular
and how many diagonals it has on each processor.
2. Use a new Importer constructor which accepts an array telling it which
processor each remote column index comes from. This way Tpetra doesn't have
to communicate to obtain that information itself.

Nalu changes to utilize Mark Hoemmen's recent Tpetra optimizations

---

include/master_element/Pyr5CVFEM.h
include/master_element/Wed6CVFEM.h
src/master_element/Pyr5CVFEM.C
src/master_element/Wed6CVFEM.C
unit_tests/UnitTestKokkosMEBC.C

* The masking operation was unnecessary after the switch to using uniform collection of side ordinals.  Additionally, the wedge had an error where it was accessing some uninitialized values.

Clean up SIMD face_grad_op for pyr/wedge

---

src/master_element/Pyr5CVFEM.C

Should be last PR before we sync to nalu-wind.

Allow for shifted at all pyr5 faces as we use a different basis.

---

include/AssembleMomentumEdgeOpenSolverAlgorithm.h
include/AssembleMomentumElemOpenSolverAlgorithm.h
include/kernel/MomentumOpenAdvDiffElemKernel.h
src/AssembleMomentumEdgeOpenSolverAlgorithm.C
src/AssembleMomentumElemOpenSolverAlgorithm.C
src/kernel/MomentumOpenAdvDiffElemKernel.C

Notes:
a) for element-based, assumed rho*uj was interpolated together.. I need to
remove the separate interpolation feature since I have not run with this
in the history of nalu variable desnity.

New momentum entrainment alg must correct for mesh motion

---

include/DataProbePostProcessing.h
include/InitialConditions.h
include/MaterialProperty.h
include/MaterialPropertys.h
include/Realm.h
reg_tests/test_files/dgNonConformal/dgNonConformal.i
src/EnthalpyEquationSystem.C
src/MaterialProperty.C
src/MaterialPropertys.C
src/Realm.C

Use cases for multiphysics requires multi-matrial. This is mostly
due to conjugate heat transfer applications that will use one single
realm.
* Simple restructuring of Material parsing:
******** Newly supported multi-material approach:
```
material_properties:
properties:
- name: mat_one
target_name: [block_10]
- name: density
type: constant
value: 1.0
- name: specific_heat
type: constant
value: 1.0
- name: thermal_conductivity
type: constant
value: 1.0
- name: mat_two
target_name: [block_20]
- name: density
type: constant
value: 1.0
- name: specific_heat
type: constant
value: 1.0
- name: thermal_conductivity
type: constant
value: 1.0
```
******** Routine block is still supported (this work is concentrating on a temperature-form approach)
``` …
```

Support multi-material approaches in Nalu

---

include/user_functions/PowerlawVelocityAuxFunction.h
src/LowMachEquationSystem.C
src/user_functions/PowerlawVelocityAuxFunction.C

* Added infrastructure to allow for a specified velocity
at an open bc.
* Add power_law to initial, inflow (cont/mom).
Notes:
a) Specify known x-velocity u_k at known y-coord, c_k along with alpha:
u_x = u_k * ( y / y_k )^1.0/alpha

Add new power law profile for Montoir testing

---

include/ActuatorLinePointDrag.h
include/FixPressureAtNodeInfo.h
include/NonConformalInfo.h
reg_tests/test_files/ablNeutralEdge/ablNeutralEdge.i
reg_tests/test_files/actuatorLine/actuatorLine.i
reg_tests/test_files/fluidsPmrChtPeriodic/fluidsPmrChtPeriodic.i
reg_tests/test_files/fluidsPmrChtPeriodic/fluidsPmrChtPeriodic_rst.i
reg_tests/test_files/heatedBackStep/heatedBackStep.i
reg_tests/test_files/heatedWaterChannelEdge/heatedWaterChannelEdge.i
reg_tests/test_files/heatedWaterChannelEdge/heatedWaterChannelEdge_rst.i
reg_tests/test_files/waleElemXflowMixFrac3.5m/waleElemXflowMixFrac3.5m.i
src/ActuatorLinePointDrag.C
src/NonConformalInfo.C
src/PeriodicManager.C
src/SolutionOptions.C
src/xfer/Transfer.C

* Deprecate boost search; only stk::kdtree is now supported
* Remove search method line commands from input files. If we move
to a new NGP approach, we can activate in once more. Rather than
strip out all of the code and let the contsructors hard code the search
method, I left the code in place for future seach support.
Notes:
a. As [hopefully] expected, no diffs due to coarse search change

Clean out the ToDo list; boost

---

include/BuildTemplates.h
include/kernel/ScalarDiffFemKernel.h
include/master_element/MasterElementFactory.h
src/kernel/ScalarDiffFemKernel.C
src/master_element/MasterElementFactory.C

* No need to new a special FEM master element. We instantiate only
Hex8 currently.
* Wrap ipWeight in a view
* Added femMeMap_ to allow for FEM-based elements and CVFEM in one realm.
* Modified FEM kernel.

Design the FEM kernels to be more dynamic for future deployment of FEM

---

include/AlgTraits.h
include/AssembleFaceElemSolverAlgorithm.h
include/ElemDataRequests.h
include/ScratchViews.h
include/kernel/ScalarPngBcFemKernel.h
include/master_element/MasterElement.h
include/master_element/Tet10FEM.h
src/ScratchViews.C
src/kernel/ContinuityOpenElemKernel.C
src/kernel/MomentumOpenAdvDiffElemKernel.C
src/kernel/MomentumSymmetryElemKernel.C
src/kernel/ScalarFluxPenaltyElemKernel.C
src/kernel/ScalarPngBcFemKernel.C
src/master_element/Tet10FEM.C
unit_tests/UnitTestKokkosMEBC.C

* Add face_grad_op for FEM
* Modify Scratch and ElemData interface. In reality, we do not
need things like dndx_fc_scs and dndx_fc_fem as they
both operate on numIps. dndx_scs and dndx_scv are useful
while dndx_fem starts looking more like dndx_scs... For another day..
* Simplified the logic to fold support dndx_fc for FEM. This means that we are
likely never going to support mixed methods, e.g., dndx_fc_scs and
dndx_fc_fem in the same PDE solve. This seems safe as I have only ever
done this for DOM NSO stabilization.
* Added Tri6Tet10 AlgTraits.
* Share face shape function extraction for CVFEM and FEM
* modify unit test to remove fc_scs

Support exposed face/element FEM-based algorithms

---

include/LowMachFemEquationSystem.h
include/ScratchViews.h
src/LowMachFemEquationSystem.C
src/ScratchViews.C
src/kernel/ContinuityOpenElemKernel.C
src/kernel/ContinuityOpenFemKernel.C
src/kernel/MomentumOpenAdvDiffElemKernel.C
src/kernel/MomentumOpenAdvDiffFemKernel.C
src/kernel/MomentumSymmetryElemKernel.C
src/kernel/ScalarFluxPenaltyElemKernel.C
unit_tests/UnitTestKokkosMEBC.C

* fix a numFaceIp error  formaly numFemIp
* add face ME pre-reqs off of faceData not elemData
* missing coordinates registration off of faceData
* another missing coord on faceData
* modify design for derivatives. Only FEM requires deriv_fc for a face:elemnet
algorithm (purely off of the face for things like face normal and face det_j)
while deriv_fc_elem is required for face grad ops. This makes things cleaner.
* deploy the consistent usage of the name "dndx_fc_elem" - just to be overly
specific. At present, there is no need for a dndx_fc usage, however, adding
the _elem really drives the point.
* wrong ME for face_grad_op_fem
* deal with IR loop - needs to be npf
* mapping between local ir face node and global number on the matrix
Notes:
a) Mess of a design/consistency when we decide we …

Towards support for FEM-based open bc: low-Mach fluid flow

---

src/ComputeSSTMaxLengthScaleElemAlgorithm.C
src/ShearStressTransportEquationSystem.C

* as per RCK's find
No diffs noted (coverage exists in elem backstep case)

Add parallel and peridoc reductions for SST/DES min-wall field

---

src/master_element/Tet10FEM.C

* AssembleCourantReynoldsFemAlgorithm calls through to the
non-NGP master elements. Here, it was found that an error in
the indexing into the derivative existed.
Notes:
a) Re and Courant numbers look far more sane. However, gij has yet
to include the proper scalings to deal with node ordering as
per FS -> another day...

Index error for Tet10 derivative (non-NGP)

---

include/AveragingInfo.h
include/TurbulenceAveragingPostProcessing.h
include/master_element/Pyr5CVFEM.h
include/master_element/Quad42DCVFEM.h
include/master_element/Tet4CVFEM.h
include/master_element/Tri32DCVFEM.h
include/master_element/Wed6CVFEM.h
reg_tests/test_files/heatedWaterChannelElem/heatedWaterChannelElem.i
src/AveragingInfo.C
src/TurbulenceAveragingPostProcessing.C
src/master_element/Pyr5CVFEM.C
src/master_element/Quad42DCVFEM.C
src/master_element/Tet4CVFEM.C
src/master_element/Tri32DCVFEM.C
src/master_element/Wed6CVFEM.C

Activate via: compute_dissipation_rate: yes
* compute CVFEM-based eps at the element. Integrate over the SCV ips
field name is "dissipation_rate"
* add grad_op for all SCV elements
* moved around a few member functions for derivatives and grad_ops to
be able to share between SCS and SCV
* add postP for eta to rtest

Add dissipation rate post processing

---

include/AveragingInfo.h
include/TurbulenceAveragingPostProcessing.h
src/AveragingInfo.C
src/TurbulenceAveragingPostProcessing.C

* Compute Pk = -\bar{rho}*Rij*d\bar{u}i/dxj
Activate via: compute_production: yes
Notes:
a) We lump Rij to avoid interpolation while interpolating density and
computing a scvIp grad_op. We could probably shift to have all of the
calculations at the same location. However, for standard RANS, we generally
follow this procedure (pick and choose locations of evaluations).

Add post processing of elemental Pk

---

include/DataProbePostProcessing.h
reg_tests/test_files/heatedWaterChannelEdge/heatedWaterChannelEdge_rst.i
src/DataProbePostProcessing.C

* re-work the data probes to support line_of_site and ring specifications:
data_probes:
output_frequency: 5
search_tolerance: 1.0e-3
search_expansion_factor: 2.0
- name: probe_volume
from_target_part: block_1
line_of_site_specifications:
- name: probeLine_zero
number_of_points: 100
tip_coordinates: [-0.005, 0.0, 0.1]
tail_coordinates: [0.005, 0.0, 0.1]
ring_specifications:
- name: probeRingFrontOne_one
number_of_points: 16
unit_normal: [0.0, 0.0, -1.0]
origin_coordinates: [0.0, 0.0, 0.1]
seed_coordinates: [0.0, 2.5e-3, 0.1]
output_variables:
- field_name: velocity
field_size: 3
- field_name: reynolds_stress
field_size: 6
Note:
a) tested in 2D and 3D. 2D drove a need to save a vector of arrays...
b) can lift to Iris now

New type of data probe averaging: Ring

---

include/DataProbePostProcessing.h
reg_tests/test_files/heatedWaterChannelEdge/heatedWaterChannelEdge_rst.i
src/DataProbePostProcessing.C

Goal: Allow for easy averaging for radially symmetric flows.
* re-arrange design to allow for a set of circular/ring data probes
* input file changes for ring case
Rule:
a) One part per ring name. Other attempts were too clunky with explosion of parts.
b) Each ring starts at the tail coordinates and rotates about the origin and
axis for each of the specified number of points. Then, dx is added based
on the line specification (can be one) and repeats. The log file respects
this ordering.
Complete Example:
data_probes:
output_frequency: 1
search_tolerance: 1.0e-6
search_expansion_factor: 2.0
- name: probe_volume
from_target_part: [Unspecified-2-HEX]
line_of_site_specifications:
- name: 25C_wale_probeCenterImpinge
number_of_points: 20
tip_coordinates:  [0.0, 0.0, -0.03] …

New ring data probe infrastructure

---

include/DataProbePostProcessing.h
src/DataProbePostProcessing.C

* No longer require inactive node from data probes given Real::get_inactive_selector():
stk::mesh::Selector otherInactiveSelector = (
metaData_->universal_part()
& !(stk::mesh::selectUnion(interiorPartVec_))
& !(stk::mesh::selectUnion(bcPartVec_)));
The above filters all nodes that are not of interest. The Overset aspect is not shown above..
Notes:
a) Data probes created in previous simulations prevail in subsequent
even if the data probe in the new run is not created.
For example, in a previous run, a data probe was created:
For probe name: los_one Node Identifiers:
562       563       564       565
In the subsequent run, these nodes still show up in the universal part:
BEGIN universal selector output:
562 563 564 565 etc...
END   universal selector output:
However, are selected out: …

Minor clean-up to DataProbes and the inactiveSelector interface

---

include/DataProbePostProcessing.h
src/DataProbePostProcessing.C

…rship
* Exploit "generateIds" and allow for the ability to mix and match
new and old probe defintions in an arbitrary input order.
The code now supports mix/matching by looking for the original part
and assigning rank ownership based on the previous rule, not the
now "candidate" rank suggestion.
* remove probe file name tied to rank id. No need, in practice, and
new design only knows if this probe is on or off the rank.
Notes:
a) not a bad design now.
b) design of probeInfo->partName_[j] could benifit from a polymorphic
design, however, no need for today:)

New probe definitions in a restart sim affect part procId ownership

---

reg_tests/test_files/variableDensNonIso/variableDensNonIso.i
src/DataProbePostProcessing.C
src/Realm.C

* Remove spurious warnings about missing reference temp/pressure
even when none is required. This was resolved by adding the proper
tRef andpRef constant extraction to the appropriate property
evaluator call.
* remove ouput() on probes - not required and a left over from previous
debugging.
* high-level reference value specification rather than sprinkled in the code
(changed Tref from 300 to 298.15).
* modified variableDensNonIso to specify Tref = 300. It is somewhat odd to see
a warning about a missing reference temperature in a variable density
non-isothermal flow, however, for a constant Cp:
h = Int Cp dT = \bar{Cp} * ( T - Tref )

Add reference extraction to germane prop eval calls

---

src/DataProbePostProcessing.C
src/InputOutputRealm.C
src/TimeIntegrator.C

* Activate DataProbes in InputOutput realm. This allows
for decoupling of data probes in DNS runs with super-probed
specifications..
* Changed DataProbes to register a vector for velocity_probe. This
follows inputOutput realm registration and turb averaging.
Sample input:
```
Simulations:
- name: sim1
time_integrator: ti_1
optimizer: opt1
realms:
- name: ioRealm
mesh: output/elem100C_wale_Rm1.e
type: initialization
field_registration:
- field_name: velocity
target_name: [Unspecified-2-HEX, Unspecified-3-HEX, Unspecified-4-HEX, Unspecified-5-HEX, Unspecified-6-HE
X, Unspecified-7-HEX]
field_size: 3
field_type: node_rank
- field_name: velocity_ra_one
target_name: [Unspecified-2-HEX, Unspecified-3-HEX, Unspecified-4-HEX, Unspecified-5-HEX, Unspecified-6-HE
X, …
```

Allow for inoput output region to post process

---

include/ComputeWallFrictionVelocityAlgorithm.h
include/LowMachEquationSystem.h
include/WallFunctionParamsAlgorithmDriver.h
src/ComputeWallFrictionVelocityAlgorithm.C
src/LowMachEquationSystem.C
src/WallFunctionParamsAlgorithmDriver.C

* Create a new wall function parameters alg driver. This is due to
the new set of wall function use-cases including machine-learned
approaches.
The issue with the current design is that zeroing of fields and
parallel assembly was being conducted in the ComputeUtauAlg. This assumed
that the single algorithm would be called once with the "symbolic" pre-
and post- completed in the alg. However, if we have multiple types of
algs, we need to have this elevated so that WallFuncParamsAlgDriver
can hanlde pre and post with arbitrary types completed in the Alg.
The SurfacePostProcessingAlgDriver is the analogous use case.

Wall function params re-design

---

include/user_functions/ChannelFlowPerturbedPlugVelocityAuxFunction.h
src/LowMachEquationSystem.C
src/user_functions/ChannelFlowPerturbedPlugVelocityAuxFunction.C

function.  This initial condition consists of a plug base flow in
the x-direction that satisfies no-slip at the y-constant boundaries,
with velocity perturbations added to all three velocity components.
The magnitude of the perturbations is 5% of the local base flow, and
are constructed from sin and cos functions so that the solution is
periodic in the x- and z-directions.  The user-supplied parameter list
is: [u_m, Lx, Ly, Lz], where u_m is the centerline base velocity and
Lx, Ly, and Lz are the domain lengths in each coordinate direction.

Added 'ChannelFlowPerturbedPlug' user-defined initial condition

---

unit_tests/UnitTestEigenDecomposition.C

Coming changes to stk-simd will use a different type for the
._data member, which won't have operator[].
stk-simd is going to use Dan Ibanez' kokkos-simd prototype
as a backend. That prototype mirrors a proposed simd addition
to the C++23 standard. Additionally, it adds support for a
couple of instruction-sets that stk-simd doesn't currently
support, namely ARM and IBM/POWER.

Fix simd usage to not access the '.data' member's operator[]

---

include/MeshMotionInfo.h
include/Realm.h
include/SolutionOptions.h
src/MeshMotionInfo.C
src/Realm.C
src/SolutionOptions.C

Usage:
solution_options:
name: myOptions
initial_mesh_displacement:
- name: staticBlock
target_name: block_1
unit_vector: [0.0,0.0,1.0]
compute_centroid: no
angle: 10.0
- name: fixedRotBlock
target_name: block_2
unit_vector: [0.0,0.0,1.0]
compute_centroid: no
angle: 10.0

Allow for initial mesh displacement

---

include/SolutionNormPostProcessing.h
include/user_functions/ConcentricAuxFunction.h
src/AssembleHeatCondIrradWallSolverAlgorithm.C
src/AssembleHeatCondWallSolverAlgorithm.C
src/SolutionNormPostProcessing.C
src/pmr/RadTransWallElemKernel.C
src/pmr/RadiativeTransportEquationSystem.C
src/user_functions/ConcentricAuxFunction.C

* add "concentric" for norms. Allow specification of norm targets rather
than blind physics targets. All rtests already where using the target
interface. As such, it was silently neglected before.
* clean up higher-order for heat cond and pmr. Code was using nn = ip rather
than ipNodeMap.

Support HO PMR solves and concentric sphere verification case

---

include/PeriodicManager.h
include/Realm.h
src/ComputeSSTMaxLengthScaleElemAlgorithm.C
src/PeriodicManager.C
src/Realm.C
src/ShearStressTransportEquationSystem.C

In most periodic field updates, we want a m+=s; s=m;
However, for SST, the miniumum normal distance to a wall field
was clipped. To ensure proper consistency of this nodal field between
m and s, a periodic_update was processed. However, the default behavior
summed the values rather than a simple setting s=m;
* generalized Realm::periodic_field_update() to allow for addSlaves
and setSlaves to be explosed to the caller. These are defaulted to
true if not specified. This approach ensures consistency of m
prevailing.

Periodic bug fix for SST min NDTW

---

docs/source/user/build_manually.rst

Removed deprecated homebrew link for SuperLU 4.3, and fixed Hypre link.

fixed typos and links in manual build instructions

---

reg_tests/xml/matches_ml_default.xml
reg_tests/xml/milestone-nc.xml
reg_tests/xml/milestone.xml
reg_tests/xml/milestone_ABL.xml
reg_tests/xml/milestone_McAlister.xml
reg_tests/xml/milestone_aspect_ratio.xml
reg_tests/xml/milestone_aspect_ratio_smooth.xml
reg_tests/xml/muelu_STV_HO.xml
reg_tests/xml/muelu_kovasznay_p7.xml

* Make the KLU request explicit in the Muelu XML so that even if someone
builds Trilinos with SuperLU, there are zero diffs (SuperLU is default
when built).

Add KLU as coarse type for all Muelu xml

---

include/Enums.h
include/NaluParsing.h
include/VolumeOfFluidEquationSystem.h
include/kernel/VolumeOfFluidElemKernel.h
include/kernel/VolumeOfFluidSucvNsoElemKernel.h
include/property_evaluator/MaterialPropertyData.h
include/user_functions/RayleighTaylorMixFracAuxFunction.h
src/ComputeGeometryInteriorAlgorithm.C
src/EquationSystems.C
src/MaterialProperty.C
src/MixtureFractionEquationSystem.C
src/NaluParsing.C
src/Realm.C
src/VolumeOfFluidEquationSystem.C
src/kernel/VolumeOfFluidElemKernel.C
src/kernel/VolumeOfFluidSucvNsoElemKernel.C
src/user_functions/RayleighTaylorMixFracAuxFunction.C

* VOF EquationSystem
* mass and advection kernel
* SUCV kernel
* connect VOF in EqSystems and kernels
* allow for VOF-based material model
* modify RayleighTaylor to support a driven cavity test; params optional
initial_conditions:
- user_function: ic_2
target_name: block_1
user_function_name:
mixture_fraction: RayleighTaylor
user_function_parameters:
mixture_fraction: [0.1, 1.0, 0.5, 0.05]
* liner system sharpening evaluation... Not so great without smoothing of
vof and, therefore, interface_normal. Remove for now..
// sharpen; d(alpha)/dtau = -d/dxj(sj); sj = [alpha*(1-alpha) + D*d(alpha)/dxk*nk]nj
* Add NSO
* dial SUCV and NSO via: [vof, sucv, nso, sucv_nso]

Support VOF transport with SUCV/NSO-based stabilization

---

include/kernel/ContinuityGclElemKernel.h
include/kernel/MomentumGclElemKernel.h
include/kernel/ScalarGclElemKernel.h
include/kernel/VolumeOfFluidGclElemKernel.h
src/LowMachEquationSystem.C
src/VolumeOfFluidEquationSystem.C
src/kernel/ContinuityGclElemKernel.C
src/kernel/ContinuityVofOpenElemKernel.C
src/kernel/MomentumGclElemKernel.C
src/kernel/ScalarGclElemKernel.C
src/kernel/VolumeOfFluidGclElemKernel.C

* Added GCL for continuity and momentum; continuity doubles with and without
balanced_force scheme; LHS included for momentum.
* Added GCL for scalars; LHS included.
* addded GCL for vof; may later deprecate for div_correction approach; LHS included.
Notes:
a) Possibly time to start deprecating some of the SuppAlgDep Elem source terms..

Port GCL to kernel

---

include/overset/OversetManagerSTK.h

New STK overset coupling generates warnings in any Clang build due to the missing line included in this PR.

Clang warning fix

---

include/Enums.h
include/VolumeOfFluidEquationSystem.h
reg_tests/test_files/vofSlosh/vofSlosh.i
reg_tests/test_files/vofSphereDrop/vofSphereDrop.i
reg_tests/test_files/vofWaveGenerator/vofWaveGenerator.i
src/VolumeOfFluidEquationSystem.C

* Allow for property specification of surface_tension;
field name; surface_tension
material_properties:
target_name: [block_1, block_2]
- name: surface_tension
type: constant
value: 0.01
* Added calculation of interface curvature;
field name; interface_curvature
Notes:
a) Need kappa_surfaceTension_ip*d(alpha)/dxj_ip*nj*dS to
vdot and LHS kernel - if d(alpha)/dxj != 0
b) Need the same ip evaluation (normalized by density) in the Gjph algorithm.
c) No need for new momentum source term - everything is hidden in Gjph...

Towards full BF algorithm

---

include/overset/AssembleOversetSolverConstraintAlgorithm.h
src/EquationSystem.C
src/overset/AssembleOversetSolverConstraintAlgorithm.C

For the BF alforithm, the system is: 1/rho*dp/dx*Area = 1/dt*v*Area
In order to have the LHS scaled properly, approximate this scaling
as (dualVolume^1/nDim)/rho
Scale the entire row by this scaling factor
* Added scaling factor for constraint alg when BF is active for
continuity. Approximate this as element averaged-quantities.
Notes:
a) In time, we can elevate thsi scaling per system.
b) Scaling does help linear system convergence substantially when the VoF
is moving through the overset pathc.

Density scaling of the continuity equation when using BF

---

src/LowMachEquationSystem.C

This change fixes a potential issue with dp/dx when simulating moving mesh cases when using overset. dp/dx is NaN inside of removed regions while using overset. These NaN values can appear in the solution when a removed cell emerges into the solution requiring a fringe reconstruction.

dpdx fringe update

---

include/Enums.h
include/TurbKineticEnergyEquationSystem.h
include/TurbKineticEnergyKsgsNodeSourceSuppAlg.h
include/TurbViscKsgsAlgorithm.h
include/kernel/TurbKineticEnergyKsgsDesignOrderSrcElemKernel.h
include/kernel/TurbKineticEnergyKsgsSrcElemKernel.h
src/LowMachEquationSystem.C
src/TurbKineticEnergyEquationSystem.C
src/TurbKineticEnergyKsgsNodeSourceSuppAlg.C
src/TurbViscKsgsAlgorithm.C
src/kernel/TurbKineticEnergyKsgsDesignOrderSrcElemKernel.C
src/kernel/TurbKineticEnergyKsgsSrcElemKernel.C

* new turbulence model, lr_ksgs
* add min distance as a required variable (with restart)
* coded projection of d(sqrt(tke)/dxj for non-design order.
* generalize ksgs node loop and kernel (including design order)
for the design-order, I do not use the nodal field for d(sqrt(tke)/dxj
* folded in lr_ksgs to TurbViscKsgs
* logic check, need to be consolidated or edge-based for lr_ksgs
to be supported.
Notes:
a) All of the source term methods have a fake out of gathering low-Re
terms and scalings of zero and the like. This is the easiest
way to avoid a proliferation of methods for EBVC and CVFEM.
b) Tested on Re395 with a great set of outcomes.
c) CVFEM only works with consolidated.
d) Why does UnitTest infrastructure provide negative values of density through
a trigometric interface? Not …

Low-Reynolds correction to k_sgs via Inagaki (2011)

---

reg_tests/xml/matches_ml_default.xml
reg_tests/xml/milestone-nc.xml
reg_tests/xml/milestone.xml
reg_tests/xml/milestone_ABL.xml
reg_tests/xml/milestone_McAlister.xml
reg_tests/xml/milestone_aspect_ratio.xml
reg_tests/xml/milestone_aspect_ratio_smooth.xml
reg_tests/xml/milestone_aspect_ratio_smooth_s.xml
reg_tests/xml/muelu_STV_HO.xml
reg_tests/xml/muelu_kovasznay_p7.xml
reg_tests/xml/readme.txt
reg_tests/xml/vofBuoy.xml

* change in Muelu XML. phase2 line command is gine (causes a throw) in favor
of: "aggregation: match ML phase2a". However, this line command is
false.
* remove old line command. Defaults in Muelu are such that match ML phase2a is false.
Notes:
a) no diffs [expected]

Remove aggregation: phase2

---

.gitmodules

This allows the usage of SSH authentication with GitHub if you are using SSH authentication for the main Nalu repo.  See:
* https://nalu.readthedocs.io/en/latest/source/developer/testing.html?highlight=cdash#testing-nalu
But if you are using HTTPS authentication for the main Nalu repo, then git submodule will use HTTPS authentication for the submodules as well.
And this works better if you want to mirror these repos on an internal GitLab site, for example. 
This change removes two of the big disadvantages of using git submodues (i.e. 1. killing the distributed aspect of Git and 2. locking your developers into an authentication protocol.)

Use relative submodule so that we can use SSH authentication if desired

---

src/TpetraLinearSystem.C
unit_tests/UnitTestTpetra.C

Fixes host of deprecated code in Tpetra routines through the use of Kokkos::Views rather than Teuchos. Type definitions in Tpetra are used rather than directly creating Kokkos::Views to ensure that Device/Host memory layouts, etc are correct no matter the system.

Move Tpetra over to Kokkos Views

---

include/MeshMotionInfo.h
include/overset/OversetManagerSTK.h
src/MeshMotionInfo.C
src/SixDofSurfaceForceAndMomentAlgorithm.C
src/SolutionOptions.C

This change includes the ability to add tethers to six-dof moving objects as well as fixes an issue with cylindrical overset cutting.

tethers + cylinder fix

---

include/FieldTypeDef.h
src/ExplicitFiltering.C
src/LowMachEquationSystem.C

* small things here and there, really. 2d_quad9_helium now back with us again.
Notes:
a) FieldBase... What is that now?
stk::mesh::FieldBase *theField = metaData.get_field(stk::topology::NODE_RANK, fieldName);
vs
stk::mesh::Field<double> *theField = metaData.get_field<double>(stk::topology::NODE_RANK, fieldName);
Does the FieldBase call work since the field was registered elsewhere with a specific type?

Minor clean-up on new STK field registration

---

include/ExplicitFiltering.h
include/FieldFunctions.h
include/master_element/Quad92DCVFEM.h
reg_tests/test_files/laboratory/2d_quad9_helium/2d_quad9_helium.i
src/ExplicitFiltering.C
src/FieldFunctions.C
src/Realm.C
src/master_element/Quad92DCVFEM.C

* add scv residual for momentum.
* allow for dual nodal volume normalization; new field function field_normalize() via a scalar normalization: y[i] = y[i]/x
* code scv grad op for quad9 (non-ngp was missing and required)
Notes:
a) deprecate scs residual as it would require boundary contributions (stashed).

explicitly filtered residual support

---

include/user_functions/TableAuxFunction.h
reg_tests/test_files/ductElemWedge/ductElemWedge.i
src/LowMachEquationSystem.C
src/TurbKineticEnergyEquationSystem.C
src/user_functions/TableAuxFunction.C

* velocity and tke table support via:
user_function_name:
velocity: table
user_function_parameters:
velocity: [0, 1, ---> component (0,1,2), and interpolate in x,y,z-direction (0,1,2) or time (3)
0.00000000, 0.00000,
0.01437268, 0.39153,
0.04087776, 0.44427,
0.07042084, 0.46362,
0.09905644, 0.50683,
0.13407968, 0.51429,
0.20199564, 0.51727,
0.23793224, 0.51758,
1.00000000, 0.51758]
For now, use a simple pair, or 2D table; can generalize as needed.
* modified ductElemWedge rtest to use table
Notes:
a) I tried a simple n interpolation, STL-based, and binary search. STL was
only a factor of 2-ish for even large tables (like 100K). As such,
proceeded with the STL-based since the code was so simple.
See the Nalu 1.0 release (TablePropsAlg for a historic binary search)

Add one-d table support

---

include/user_functions/Table2dAuxFunction.h
src/mesh_motion/MeshDisplacementEquationSystem.C
src/user_functions/Table2dAuxFunction.C

* Support linear 2D interpolation for the DAC/CDR use case, where surface topology is derived from a scan.
The user provides the following info:
wall_user_data:
user_function_name:
mesh_displacement: table2d
user_function_parameters:
mesh_displacement: [2, 0, 1, 101, 51, 1.0]
user_function_string_parameters:
mesh_displacement: [single_m100xp100_m50xp50.dat]
Table2dAuxFunction outlines the data management requirements.

simple linear interpolation for a 2D table

---

CMakeLists.txt

* as per https://github.com/trilinos/Trilinos/issues/12326

Modify and update CMake

---

include/SolutionOptions.h
src/Realm.C

* Avoid bitwise comparisons for bools.
* Avoid duplicate logic in Realm and SolutionOptions
Resolves https://github.com/NaluCFD/Nalu/issues/667 in addition to cleaning up compiler warnings

Clean-up logical comparisons as per intel-one-api

---

include/SolutionOptions.h
reg_tests/test_files/milestoneRunConsolidated/milestoneRunConsolidated.i
src/SolutionOptions.C
src/TurbKineticEnergyEquationSystem.C

* added:
dynamic_turbulence_clipping_factor: {double lamFac}
This option clips dynamic coefficeints to a fraction of the laminar
viscosity. A value of 0 allows for no negativity, while that of unity
allows for a tvisc to be -visc. Default is zero (a change from the hard-coded
0.5 value).
* Modify rtest to ensure pass; specifically, added the new line command for the previous defalut of 0.5 (the test first diffed without this line)

Elevate clipping option to the input file

---

include/TurbulenceAveragingPostProcessing.h
reg_tests/test_files/heliumPlume/heliumPlume.i
reg_tests/test_files/heliumPlume/heliumPlume_rst.i
src/TurbulenceAveragingPostProcessing.C

* allow for a start time, start_time: {default==0}
* modifed heliumPlume rtest; tested and all looks well; no diffs expected

Add average start time

---

unit_tests/UnitTestHelperObjects.h
unit_tests/UnitTestLinearSystem.h

Resolves Nalu unit test issue noted in https://github.com/trilinos/Trilinos/issues/13351 specifically, a view allocation within a parallel_for
@alanw0 added as a sanity check review, although all tests now pass.

UnitTest fix past Kokkos update
