NaluCFD/Nalu

CMakeLists.txt
unit_tests/UnitTestHex27FaceNodeOrdering.C
unit_tests/UnitTestHexMasterElements.C
unit_tests/UnitTestUtils.C
unit_tests/UnitTestUtils.h

Starts adding in some unit tests for the master element functions in Nalu.  Tests interpolation and gradient operations on reference hex elements.
@alanw0 , @spdomin

Start adding some master element unit tests

---

CMakeLists.txt
build/do-configNalu_debug
include/BoundaryConditions.h
include/InitialConditions.h
include/NaluParsing.h
include/NaluParsingHelper.h
nalu.C
src/ActuatorLine.C
src/BoundaryConditions.C
src/DataProbePostProcessing.C
src/EquationSystems.C
src/InitialConditions.C
src/InputOutputRealm.C
src/LinearSolverConfig.C
src/LinearSolvers.C
src/MaterialPropertys.C
src/NaluParsing.C
src/OutputInfo.C
src/PostProcessingInfo.C
src/Realm.C
src/Realms.C
src/Simulation.C
src/SolutionNormPostProcessing.C
src/SolutionOptions.C
src/TimeIntegrator.C
src/TurbulenceAveragingPostProcessing.C
src/xfer/Transfer.C
src/xfer/Transfers.C

Rtest Begin:
..periodic3dElemNp1........... PASSED:  6.8  s
..periodic3dElemNp4........... PASSED:  2.6  s
..periodic3dElemNp8........... PASSED:  1.7  s
..periodic3dEdgeNp1........... PASSED:  3.2  s
..periodic3dEdgeNp4........... PASSED:  1.6  s
..periodic3dEdgeNp8........... PASSED:  1.1  s
..quad9HC..................... PASSED:  54.5  s
..steadyTaylorVortex.......... PASSED:  72.8  s
..hoVortex.................... PASSED:  86.0  s
..hoHelium.................... PASSED:  392.5  s
..dgNonConformal.............. PASSED:  2.8  s
..dgNonConformalEdge.......... PASSED:  2.9  s
..dgNonConformalFluids........ PASSED:  54.4  s
..dgNonConformalFluidsEdge.... PASSED:  45.7  s
..dgNonConformal3dFluids...... PASSED:  73.5  s
..dgNonConformal3dFluidsP1P2.. FAILED:  162.6  s   max diff: …

Upgrade to new yaml-cpp interface. All tests perform the same as the head of master branch

---

unit_tests/UnitTestKokkosViews.C

I changed the unit test to compute the discrete Laplacian, and compared the result with the exact result for a quadratic polynomial.  The max error for this test on my local machine is about 1e-11, and I put the tolerance at 1e-10.

Modify KokkosView unit test to compute the discrete Laplacian

---

unit_tests/UnitTestKokkosViews.C

Fixes the selectors to get the test working in parallel.

Fix KokkosView unit test in parallel

---

cmake/README.md
cmake/ctest_common.cmake
cmake/ctest_peregrine_gcc.cmake
cmake/ctest_peregrine_intel.cmake

Also added CTest instructions.

Minor modifications to make it easier to add a new platform.

---

include/CoriolisSrc.h
include/MomentumCoriolisSrcNodeSuppAlg.h
src/CoriolisSrc.C
src/MomentumCoriolisSrcNodeSuppAlg.C

* The CoriolisSrc class contains the setup data and calculations for the
Coriolis source term.  This prevents code duplication between the Node and
Element source term algorithms.  Each of these algorithms will now contain
a CoriolisSrc object with the necessary data.

Added the CoriolisSrc class

---

CMakeLists.txt

Adding install targets to allow for 'make install' while preserving existing functionality.

Adding install targets

---

include/master_element/MasterElement.h
src/Realm.C
src/master_element/MasterElement.C
unit_tests/UnitTestHex27FaceNodeOrdering.C
unit_tests/UnitTestHexMasterElements.C
unit_tests/UnitTestMetricTensor.C
unit_tests/UnitTestUtils.C
unit_tests/UnitTestUtils.h

* Add a factory method to MasterElement for
* Create reference elements of any supported element rank topology 
* Unit test doesn't check pyramid elements right now

Add unit test for metric tensor calculations

---

include/AlgTraits.h
include/HeatCondEquationSystem.h
include/ScalarDiffElemSuppAlg.h
include/ScalarDiffFemSuppAlg.h
include/SupplementalAlgorithmBuilder.h
include/SupplementalAlgorithmBuilderLog.h
include/user_functions/SteadyThermal3dContactSrcElemSuppAlg.h
src/HeatCondEquationSystem.C
src/ScalarDiffElemSuppAlg.C
src/ScalarDiffFemSuppAlg.C
src/SupplementalAlgorithmBuilderLog.C
src/user_functions/SteadyThermal3dContactSrcElemSuppAlg.C

See  NaluCFD/Nalu#69 and NaluCFD/Nalu#70

Add a supplemental algorithm builder function

---

cmake/ctest_prepare_tests.cmake
include/ABLForcingAlgorithm.h
include/EnthalpyABLSrcNodeSuppAlg.h
include/MomentumABLForceSrcNodeSuppAlg.h
include/Realm.h
include/utils/LinearInterpolation.h
src/ABLForcingAlgorithm.C
src/EnthalpyABLSrcNodeSuppAlg.C
src/EnthalpyEquationSystem.C
src/LowMachEquationSystem.C
src/MomentumABLForceSrcNodeSuppAlg.C
src/Realm.C

Reopening pull-request #62 with squashed commits. (Github won't allow me to reopen the old pull request because a forced-push on the branch). 
Changes in addition to what was accepted in pull-request #62:
- Squashed commits to remove commits that was just code reformatting (Stefan's comment)
- Added `ablForcingEdge` test to CTest/CDash nightly test suite
Corresponding `NaluRTest` pull-request: NaluCFD/NaluRTest#11

ABL Forcing Algorithm

---

include/AlgTraits.h
include/BuildTemplates.h
include/ContinuityAdvElemSuppAlg.h
include/ContinuityAdvElemSuppAlgDep.h
include/ContinuityMassElemSuppAlg.h
include/ContinuityMassElemSuppAlgDep.h
include/ElemDataRequests.h
include/ScratchViews.h
include/SupplementalAlgorithmBuilder.h
src/ContinuityAdvElemSuppAlg.C
src/ContinuityAdvElemSuppAlgDep.C
src/ContinuityMassElemSuppAlg.C
src/ContinuityMassElemSuppAlgDep.C
src/LowMachEquationSystem.C
src/ScratchViews.C

Moved Continuity consolidated Elem Supplemental Algorithms to the new `AssembleElemSolverAlgorithm` interface.

Continuity SuppAlg refactor to work with new AssembleElemSolverAlg

---

include/master_element/MasterElement.h
src/master_element/MasterElement.C
unit_tests/UnitTestMasterElements.C
unit_tests/UnitTestMetricTensor.C
unit_tests/UnitTestUtils.C
unit_tests/UnitTestUtils.h

* Add SCV ips / shape functions for tris
* Pyramids don't pass the patch tests.  I'd have to specialize them for pyramids.
* Still missing isInElement / interpolatePoint methods for HO

Add some basic unit tests for the master element routines

---

include/user_functions/KovasznayPressureAuxFunction.h
include/user_functions/KovasznayVelocityAuxFunction.h
src/LowMachEquationSystem.C
src/SolutionNormPostProcessing.C
src/user_functions/KovasznayPressureAuxFunction.C
src/user_functions/KovasznayVelocityAuxFunction.C

Add some aux functions for the Kovasznay flow verification test

Add Kovasznay flow aux functions

---

src/MomentumAdvDiffElemKernel.C
src/ScalarAdvDiffElemKernel.C
src/ScalarUpwAdvDiffElemKernel.C

Replace `massFlowRate` data access with ScratchViews interface in Kernel `execute` method. 
The `element` argument cannot be deprecated yet until the `FEM` kernel has been updated.

Update Kernels to use ScratchViews for element data

---

include/element_promotion/LagrangeBasis.h
include/element_promotion/MasterElementHO.h
include/element_promotion/MasterElementUtils.h
src/element_promotion/LagrangeBasis.C
src/element_promotion/MasterElementHO.C
src/element_promotion/MasterElementUtils.C
unit_tests/UnitTestHOMasterElements.C

* Doesn't include isInElement for native quad9 / hex27 elements

Implement isInElement and interpolatePoint routines for promoted elements

---

include/element_promotion/MasterElementHO.h
include/element_promotion/MasterElementUtils.h
include/master_element/MasterElement.h
src/element_promotion/MasterElementHO.C
src/element_promotion/MasterElementUtils.C
src/master_element/MasterElement.C
unit_tests/UnitTestMasterElements.C

* Add isInElement and interpolatePoint for native P2
* Some cleanup for the P2 master elements. Tests show hoHelium being a bit faster on my blade.
* Expand test for isInElement and interpolatePoint

Add pyramid isInElement and interpolatePoint routines

---

include/KokkosInterface.h
unit_tests/UnitTestKokkosUtils.h

Fix build errors when `Kokkos_ENABLE_OpenMP=ON`

---

unit_tests/UnitTestFieldUtils.C
unit_tests/UnitTestFieldUtils.h
unit_tests/UnitTestRealm.C
unit_tests/UnitTestRealm.h
unit_tests/UnitTestUtils.C
unit_tests/UnitTestUtils.h
unit_tests/algorithms/UnitTestAlgorithm.C
unit_tests/algorithms/UnitTestAlgorithm.h
unit_tests/algorithms/UnitTestAlgorithmUtils.h
unit_tests/algorithms/UnitTestLESAlgorithms.C
unit_tests/algorithms/UnitTestSSTAlgorithms.C
unit_tests/kernels/UnitTestKernelUtils.C
unit_tests/kernels/UnitTestKernelUtils.h

As discussed in our standups, here is a set of unit tests for the SST/DES routines. These have been cross-checked with an independent Python script that calculates the same fields/lhs/rhs terms. Please let me know what you think. Thank you!

Unit tests for SST, SST/DES and LES Algorithms and SuppAlgs.

---

include/BuildTemplates.h
include/ContinuityAdvElemKernel.h
include/KokkosInterface.h
include/MomentumAdvDiffElemKernel.h
include/MomentumMassElemKernel.h
include/ScalarUpwAdvDiffElemKernel.h
include/nso/MomentumNSOElemKernel.h
include/nso/MomentumNSOKeElemKernel.h
include/nso/MomentumNSOSijElemKernel.h
include/nso/ScalarNSOElemKernel.h
include/user_functions/SteadyThermal3dContactSrcElemKernel.h
src/AssembleElemSolverAlgorithm.C
src/ContinuityAdvElemKernel.C
src/MomentumAdvDiffElemKernel.C
src/MomentumMassElemKernel.C
src/ScalarUpwAdvDiffElemKernel.C
src/TpetraLinearSystem.C
src/nso/MomentumNSOElemKernel.C
src/nso/MomentumNSOKeElemKernel.C
src/nso/MomentumNSOSijElemKernel.C
src/nso/ScalarNSOElemKernel.C
src/user_functions/SteadyThermal3dContactSrcElemKernel.C

- Switch sierra::nalu::DeviceSpace to Kokkos::DefaultExecutionSpace
- Fix all work arrays in Kernels to be thread safe
- Update sumInto method to force atomic updates when running in
threaded mode

Enable OpenMP Threading in Nalu

---

include/Kernel.h

* Work around an issue with Intel 16

Fix intel 16 build error

---

include/DataProbePostProcessing.h
src/DataProbePostProcessing.C

* modified line-of-sight to output the following:
Time	Coords[0]	myFieldOne[0]	myFieldTwo[0]
* removed mean and variance as per team's suggestion.
* provide banner only once per file, not per time step

Change l-o-s from sequence of variables to single row

---

reg_tests/CTestList.cmake

Added Catalyst script line for CMake configure.

Fix for ParaView Catalyst regression tests

---

docs/source/user/nalu_run/nalu_inp.rst

I documented the following options: 
- turbulence averaging
- data probes
- post processing on the surfaces. 
Let me know what you think, where I should add details, etc. Thank you!

Documented some input file options.

---

CMakeLists.txt

Since we're getting more options, I think it's nice to have them all listed together at the top. This merely does that and moves around some comments. I'm paranoid about touching the cmakelists now, so I will clean it up step by step.

Moving all available options to top of CMakeLists.

---

include/AssembleScalarFluxBCSolverAlgorithm.h
src/AssembleContinuityNonConformalSolverAlgorithm.C
src/AssembleMomentumNonConformalSolverAlgorithm.C
src/AssembleScalarFluxBCSolverAlgorithm.C
src/ComputeMdotNonConformalAlgorithm.C
src/NaluParsing.C

* clean-up; removed unused coords from scalar flux bc alg
* clean-up; reformat naluParsing from, presumably, YAML upgrade. Everyone
check for tabs in one's editor:)
clean-up; removed parallel communication for exposed area vec in NCAlg;
opposing surface does not need this.

Misc Clean-up

---

src/EnthalpyEquationSystem.C
src/MixtureFractionEquationSystem.C
src/nso/ScalarNSOKeElemKernel.C
src/nso/ScalarNSOKeElemSuppAlg.C

* Added kernel-based NSO with ke fine scale residual
Note:
a) Developed this on my mac. As such, I will modify a regression test ASAP

Add ke NSO for Z and h

---

include/AssembleTemperatureNormalGradientBCSolverAlgorithm.h
include/TurbKineticEnergyKsgsSrcElemKernel.h
src/AssembleTemperatureNormalGradientBCSolverAlgorithm.C
src/TurbKineticEnergyKsgsSrcElemKernel.C

* simple single staff contribution example in which SD used NREL and MC used SNL...

Copyright clean-up; an example to drive discussion

---

src/LowMachEquationSystem.C

This addresses a comment in #293.

Removed tensor eddy viscosity kernel interface.

---

include/AssembleFaceElemSolverAlgorithm.h
include/Kernel.h
include/ScratchViews.h
include/SharedMemData.h
include/SimdInterface.h
src/AssembleElemSolverAlgorithm.C
src/AssembleFaceElemSolverAlgorithm.C
unit_tests/kernels/UnitTestFaceElemBasic.C

AssembleFaceElemSolverAlgorithm.

Promote unit-test face-elem-alg class to

---

include/kernel/MomentumOpenAdvDiffElemKernel.h
include/kernel/MomentumUpwAdvDiffElemKernel.h
src/kernel/MomentumOpenAdvDiffElemKernel.C
src/kernel/MomentumSymmetryElemKernel.C
unit_tests/UnitTestUtils.h
unit_tests/kernels/UnitTestFaceElemBasic.C

* add (rho*uj*ui - tau_ij)njDs kernel
* elect to use mask for if (mdot > 0).
* add unit test
Notes:
a) last fixme is related to face ordinal and face_elem_node mapping. Time to
work with RCK and extend the full capability.

Add Momentum open adv/diff kernel

---

src/PecletFunction.C

Fix error in template instantation when STK SIMD is not enabled.

---

src/pmr/RadiativeTransportEquationSystem.C

* Convergence crit for inner iterations was differernt from equationSystems
level convergence check - make them the same. This avoids a disconnect between
inner and outer iterations that, in some cases, was not allowing proper convergence.
* Change the RadTransEQS convergence criteria to be a min between the scaled
nonlinear norm, i.e., current/firstInTimeStep, and the scaled scalar flux norm:
(old-new)/new. Before, it was the raw nonlinear norm.
* fix norm scaling for inner iteration use case. Needed to be sure that the first
nonlinear residual saved was, in fact, the first computed.
Now, a 20/1 and 1/20 specification behave the same:
3/20    Equation System Iteration
myRTE Iteration: 1/1
EqSystem Name:       myRTE
aver iters      = 13.3359
nonlinearResidNrm  = 5.64561e-10 scaled: …

SNL non-wind: Fix nonlinear scaling/convergence in RadTransEQS

---

src/Realm.C
src/kernel/MomentumSymmetryElemKernel.C
src/kernel/MomentumWallFunctionElemKernel.C
src/kernel/ScalarOpenAdvElemKernel.C
src/master_element/MasterElementWork.F
src/overset/TiogaSTKIface.C
unit_tests/UnitTestHOMasterElements.C

remove small issues found in EW

---

include/LinearSolver.h
include/LinearSystem.h
include/TpetraLinearSystem.h
src/Realm.C

Deprecation and leaks

---

include/mesh/Mesh.h
src/ABLForcingAlgorithm.C
src/Adapter.C
src/DataProbePostProcessing.C
src/EnthalpyEquationSystem.C
src/HeatCondEquationSystem.C
src/InputOutputRealm.C
src/LowMachEquationSystem.C
src/MassFractionEquationSystem.C
src/MixtureFractionEquationSystem.C
src/ProjectedNodalGradientEquationSystem.C
src/Realm.C
src/ShearStressTransportEquationSystem.C
src/SolutionNormPostProcessing.C
src/SpecificDissipationRateEquationSystem.C
src/TurbKineticEnergyEquationSystem.C
src/TurbulenceAveragingPostProcessing.C
src/mesh_motion/MeshDisplacementEquationSystem.C
src/overset/TiogaBlock.C
src/pmr/RadiativeTransportEquationSystem.C
unit_tests/UnitTestHexElementPromotion.C
unit_tests/UnitTestMovingAverage.C
unit_tests/UnitTestQuadElementPromotion.C
unit_tests/UnitTestRealm.C
unit_tests/UnitTestSuppAlgDataSharing.C
unit_tests/UnitTestUtils.C
unit_tests/UnitTestUtils.h
unit_tests/algorithms/UnitTestAlgorithm.C
unit_tests/algorithms/UnitTestMomentumBoussinesqSrcNodeSuppAlg.C
unit_tests/kernels/UnitTestKernelUtils.h

* Deal with the deprecated put_field by defining an interface to stk, nalu::Mesh
* Convert unit tests
* Added tensor quanity interface to nalu::mesh::put_field
* stylistic <> to "" for nalu includes

Added interface for stk::mesh::put_field

---

src/AssembleNodalGradUAlgorithmDriver.C
src/AssembleWallHeatTransferAlgorithmDriver.C
src/ComputeABLWallFrictionVelocityAlgorithm.C
src/ComputeGeometryAlgorithmDriver.C
src/ComputeMdotElemAlgorithm.C
src/ComputeTurbKineticEnergyWallFunctionAlgorithm.C
src/ComputeWallFrictionVelocityAlgorithm.C
src/SpecificDissipationRateEquationSystem.C
src/SurfaceForceAndMomentAlgorithmDriver.C
src/TpetraLinearSystem.C
src/pmr/RadiativeTransportEquationSystem.C

Pull from EW Tpetra mods

---

docs/source/theory/windEnergy.rst

corrected typo in equation 15.2

---

include/user_functions/PowerlawPipeVelocityAuxFunction.h
src/LowMachEquationSystem.C
src/Realm.C
src/mesh_motion/AssembleMeshDisplacementElemSolverAlgorithm.C
src/user_functions/PowerlawPipeVelocityAuxFunction.C

* compute vrtm only for fluids realm
* add new power law for pipe flow

Misc code additions

---

include/master_element/MasterElementFunctions.h
src/master_element/Hex8FEM.C

* generalized FEM::generic_grad_op_3d to ME::generic_grad_op_fem

FEM clean-up

---

include/AlgTraits.h
include/LinearSolverConfig.h
include/LinearSolverTypes.h
src/LinearSolver.C
src/LinearSolverConfig.C
src/TpetraLinearSystem.C

* new Muelu CreateTpetraPrecond mod
* removal of node for new Tpetra interface

Deal with new deprecation warnings through latest Trilinos update

---

include/AuxFunctionAlgorithm.h
include/NaluEnv.h
include/user_functions/SinProfilePipeFlowVelocityAuxFunction.h
nalu.C
src/AuxFunctionAlgorithm.C
src/LowMachEquationSystem.C
src/NaluEnv.C
src/Realm.C
src/user_functions/SinProfilePipeFlowVelocityAuxFunction.C

* added infrastructure for parallel communication when AuxAlgs
may call through to a field that was populated with randomness.
* provide interface to base input name for catalyst.

Add pipe flow initialization and misc clean-up

---

include/BuildTemplates.h
include/kernel/KernelBuilder.h
src/master_element/Tet10FEM.C

* fix population of exposed ips for tet10
* add infrastructure to build tri6/tet10 algs in KernelBuilder and
explicit template instantiation

Connect tri6/tet10 infrastructure

---

include/kernel/MomentumOpenAdvDiffFemKernel.h
src/kernel/MomentumOpenAdvDiffFemKernel.C

Tweaks to open

---

include/kernel/ScalarFluxPenaltyFemKernel.h
src/MixtureFractionFemEquationSystem.C
src/kernel/ScalarFluxPenaltyFemKernel.C
src/master_element/Tet10FEM.C

* activate by requesting consolidated face_elem approach
(in mixture fraction) - for wall only.
* bug fix in side_node_ordinals for Tet10.
Notes:
a) this intermediate step was taken to debug the fluids cass. Now, all
looks well with the general face-grad-op-based exposed FEM bc. The
issue seems to have been cased by the side_node_ordinals bug.

Weak FEM-based scalar flux penalty diffusion option

---

include/HeatCondEquationSystem.h
src/HeatCondEquationSystem.C
src/Realm.C

* Realm::look_ahead() manages the proper creation.
* misc divQ

Fix Turbulence Averaging Creation

---

include/HeatCondEquationSystem.h
include/NaluParsing.h
src/HeatCondEquationSystem.C
src/NaluParsing.C

Couple two thermal realms

---

include/Realm.h
src/EnthalpyEquationSystem.C
src/HeatCondEquationSystem.C
src/MassFractionEquationSystem.C
src/MixtureFractionEquationSystem.C
src/MixtureFractionFemEquationSystem.C
src/Realm.C

* uniformFlow_ and isothermalFlow_ to simply: uniform_ and isothermal_

Change Realm's member name

---

src/TpetraLinearSystem.C

This push resolves a common issue recently discovered for
edge-based and non-conformal algorithms. Specifically, a
sharedNotOwned node may be connected to an entity that is not
iterated in the initialize_connectivity() call. Therefore,
the current linSys implementation attempts to add a graph connection
that need not (and should not) exist.
For example, a simple 2D EBVC case contained a locally owned node, 33
on proc P1. This node was listed as "sharedNotOwned" on proc P2.
However, all locally owned edges that were itereated in
buildEdgeToNodeGraph() that connected node 33 were not owned by P2.
Therefore, connections[node=33] was zero.
In fact, I found this issue recently for the non-conformal implementation,
however, tracked this issue down to the fact that the current dofStatus
provides …

sharedNotOwned with zero column entries "fix"

---

src/ActuatorLinePointDrag.C
src/overset/OversetManagerSTK.C

A recent stk_search::coarse_search() optimization reversed
the calling signature for domain and range should the range size
be larger than the domain, e.g., more elements than points.
This change caused ordering differences in a few regression tests
that affected results and were determined to be order-of-operation
diffs.
For the actuator line case, each point in the AL sets a radius such
that multiple elements are found. Then, each element found has its set
of nodes pushed to a vector of nodes over which the source terms are
distributed. A different search order results in a different source
term contribution ordering. However, the "best element" remains the same.
* add a sort after stk::search::coarse_search in ActuatorLinePointDrag (new diff)
For the overset methodology, the coarse …

STK search order insulation

---

include/TurbulenceAveragingPostProcessing.h
reg_tests/test_files/heatedWaterChannelElem/heatedWaterChannelElem.i
src/TurbulenceAveragingPostProcessing.C

Allow for nodal fields: dissipation_rate_projected, dissipation_rate_filter, production_projected, production_filter

Project dissipation rate

---

src/TpetraLinearSystem.C

* dof STATUS is still a mess. Very fragile and in great need of a
redisn. This push at least allows for non-interacting dg and periodic
bcs to be properly handled... The previous implementation was confusing
the dof status for a non conformal scheme when that node was not a
perioidc node, however, periodicity was activated.
Zero diffs; several use cases testng this all work now.

clean up non-interacting periodic and non-conformal alg

---

include/SurfaceForceAndMomentAlgorithm.h
include/SurfaceForceAndMomentAlgorithmDriver.h
include/SurfaceForceAndMomentWallFunctionAlgorithm.h
include/SurfaceForceAndMomentWallFunctionProjectedAlgorithm.h
src/LowMachEquationSystem.C
src/SurfaceForceAndMomentAlgorithm.C
src/SurfaceForceAndMomentAlgorithmDriver.C
src/SurfaceForceAndMomentWallFunctionAlgorithm.C
src/SurfaceForceAndMomentWallFunctionProjectedAlgorithm.C

Not ready for prime time... Incremental

Attempt at resolving averaging issue

---

src/TpetraLinearSystem.C

Attempts to resolve slowdown noted in the following issue:
https://github.com/NaluCFD/Nalu/issues/500
However, I need to test the full set of cases on a linux box.

Provide a detailed check on periodic and ncAlg node if both are active

---

reg_tests/xml/matches_ml_default.xml
reg_tests/xml/milestone-nc.xml
reg_tests/xml/milestone.xml
reg_tests/xml/milestone_ABL.xml
reg_tests/xml/milestone_McAlister.xml
reg_tests/xml/milestone_aspect_ratio.xml
reg_tests/xml/milestone_aspect_ratio_smooth.xml
reg_tests/xml/muelu_STV_HO.xml
reg_tests/xml/muelu_kovasznay_p7.xml
reg_tests/xml/readme.txt

Change addresses failing tests due to Muelu default behavior:
https://github.com/trilinos/Trilinos/issues/7295#issuecomment-623808282
Some snippets, for example, is this a change for the better or worse?
It's difficult to say whether this is good/bad for Nalu or NaluWind.
Path forward: @spdomin will plan on testing on capability-class cases.

Change Muelu XML to support default aggregation

---

docs/source/user/build_manually.rst
src/Realm.C

* Update CMake manual build instructions to 3.17.0
* reorder overset::init to avoid null pointer selector call
on inActivePart_ - harmless move

Trilinos changes and Nalu fixes

---

include/Enums.h
include/Realm.h
include/gas_dynamics/AssembleGasDynamicsAlgorithmDriver.h
include/gas_dynamics/AssembleGasDynamicsCourantReynoldsElemAlgorithm.h
include/gas_dynamics/AssembleGasDynamicsFluxAlgorithm.h
include/gas_dynamics/AssembleGasDynamicsSymmetryAlgorithm.h
include/gas_dynamics/GasDynamicsEquationSystem.h
src/AssembleNodalGradAlgorithmDriver.C
src/EquationSystems.C
src/LowMachEquationSystem.C
src/Realm.C
src/SolutionOptions.C
src/gas_dynamics/AssembleGasDynamicsAlgorithmDriver.C
src/gas_dynamics/AssembleGasDynamicsCourantReynoldsElemAlgorithm.C
src/gas_dynamics/AssembleGasDynamicsFluxAlgorithm.C
src/gas_dynamics/AssembleGasDynamicsSymmetryAlgorithm.C
src/gas_dynamics/GasDynamicsEquationSystem.C

* Added GasDyn EqSYS, with plumbing from EqSys-s
* Edge-based RHS interior contribution; wrapped in an AlgDriver (-NOC)
* Nodal-based RHS interior mass contribution; wrapped in AlgDriver
* Added bc infrastructure - for primitives
* Aux variable population from IC primitives
* post update aux variables
* added full diffusion for energy
* Added symmetry boundary alg
* added property infrastruture
* add Courant algorithm that includes speed of sound (kept this a
seperate class so as to not affect low-Mach.
* add calculation of temperature
* let options block be optiona (AUSM does not need options)
Ready to test; incremental push...

AUSM-based gas dynamics solver

---

include/gas_dynamics/AssembleGasDynamicsNonConformalAlgorithm.h
include/gas_dynamics/GasDynamicsEquationSystem.h
src/gas_dynamics/AssembleGasDynamicsNonConformalAlgorithm.C
src/gas_dynamics/GasDynamicsEquationSystem.C

* no diffusion yet.
* added diffusion
Notes:
a) ST works great; next steps:
b) activate diffusion
c) add test coverage

Add ncAlg for gasDyn

---

src/gas_dynamics/GasDynamicsEquationSystem.C

* Shocktube runs great.
Notes:
a) Issue with data probes and overset - need inactive...

AUSM Overset support; static mesh

---

include/gas_dynamics/AssembleGasDynamicsOpenAlgorithm.h
src/gas_dynamics/AssembleGasDynamicsFluxAlgorithm.C
src/gas_dynamics/AssembleGasDynamicsOpenAlgorithm.C
src/gas_dynamics/GasDynamicsEquationSystem.C

* Added open bc to support inflow/open approachs. Supersonic and transonic
tested; low-speed needs some additional testing and modifications.
* Add missing files

Outflow bc

---

docs/source/user/build_manually.rst

Fixed link to older zlib version 1.2.11.

Update build_manually.rst hyperlink to zlib

---

src/TpetraLinearSystem.C
unit_tests/UnitTestTpetra.C

This fixes the latest Trilinos deprecation warnings. As far as I can tell this is all that is left. There are still some deprecation warnings within Trilinos itself that hopefully will get sorted soon.

Fix Trilinos deprecations

---

include/TpetraLinearSystem.h
src/TpetraLinearSystem.C

This fixes the remaining Trilinos deprecation related errors.

Trilinos deprecation fixes

---

include/SolutionOptions.h
nalu.C
src/HeatCondEquationSystem.C
src/LinearSolver.C
src/NaluParsing.C
src/SolutionOptions.C
src/TpetraLinearSystem.C
src/kernel/ThermalSrcElemKernel.C
unit_tests.C
unit_tests/UnitTestMasterElements.C

* add external data flag for walls; allows for one-way thermal
* deal with a couple Kokkos deprecation warnings
* deal with STK deprecation warnings

Support new thermal source term (and dep cleanup)

---

include/SolutionOptions.h
include/kernel/ThermalSrcElemKernel.h
nalu.C
src/HeatCondEquationSystem.C
src/LinearSolver.C
src/NaluParsing.C
src/SolutionOptions.C
src/TpetraLinearSystem.C
src/kernel/ThermalSrcElemKernel.C
unit_tests.C
unit_tests/UnitTestMasterElements.C

not sure how I missed this... argh.

Volumetric source

---

include/SolutionOptions.h
include/VolumeOfFluidEquationSystem.h
src/EquationSystems.C
src/SolutionOptions.C
src/VolumeOfFluidEquationSystem.C

* allow for NDTW to be a field for more advanced DAC/CDR initial conditions..
* Move init for vof wetted column alg to before property evaluation.

add IC wetted column

---

src/InputOutputRealm.C
src/Realm.C

Address: https://github.com/trilinos/Trilinos/issues/11487

Remove direct Ioss header includes.

---

src/TurbulenceAveragingPostProcessing.C

* vorticity post-processing was dimensioned "nDim", rather that "3" since a 2D and 3D sim produces a 3D vorticity field.
Notes:
a) 2D and 3D are now working well.

Fix 2D vorticity

---

src/EquationSystems.C
unit_tests/UnitTestKokkosME.h
unit_tests/UnitTestLinearSystem.h

Notes:
a) still confused why the deprecation warning did not trigger on this STK deprecation, however, I think we have them all complete now.

Missed a couple of deprecations

---

src/TurbKineticEnergyEquationSystem.C

* Mising periodic sum; order changes.
Notes:
a) production run, with periodic, is running well now.

Dynamic kSGS periodic fix

---

src/InputOutputRealm.C

Support IO Realm averaging

---

src/InputOutputRealm.C

Reverts NaluCFD/Nalu#668
Problem with probes.. Needs more thought/work.

Revert "Support IO Realm averaging"

---

unit_tests/UnitTestUtils.C

* resolves: https://github.com/trilinos/Trilinos/issues/12531

Fix nested mesh-mods

---

src/SurfaceForceAndMomentWallFunctionProjectedAlgorithm.C

Revert "resolve post processing ode factors"
